/**
 *
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 13, 2025 17:52
 * @component Area
 * @description The area element represents either a hyperlink with some text and a corresponding area on an image map, or a dead area on an image map.
 */

export default {
  title: "HTML5/Void Elements/Area",
  tags: ["autodocs"],
  parameters: {
    actions: {
      handles: ['change'],
    },
    layout: "centered",
    componentSubtitle: "Void Element",
    docs: {
      inlineStories: true,
      source: true,
      description: {
        component: "The area element represents either a hyperlink with some text and a corresponding area on an image map, or a dead area on an image map.",
      },
    },
  },
  argTypes: {
    accesskey: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    alt: {
      type: {
        name: "string",
        required: true
      },
      description: "Specifies alternative text to be displayed when the image cannot be rendered.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    autocapitalize: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "none", "sentences", "words", "characters"],
    },
    autofocus: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    classProp: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    contenteditable: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "true", "false", "inherit"],
    },
    coords: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the coordinates of the shape in a rectangular area or a polygonal area on an image map.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    data: {
      type: {
        name: "object",
        required: false
      },
      description: "Custom data attributes (data-*). Provide an object with key-value pairs.",
      defaultValue: {},
      control: {
        type: "object"
      },
    },
    dir: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "ltr", "rtl", "auto"],
    },
    download: {
      type: {
        name: "string",
        required: false
      },
      description: "Indicates that the linked content should be downloaded rather than displayed.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    draggable: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    hidden: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    href: {
      type: {
        name: "string",
        required: true
      },
      description: "Specifies the URL of the linked resource. Special protocols such as mailto: or tel: can be used.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    hreflang: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the language of the linked resource.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    id: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    inputmode: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "none", "text", "decimal", "numeric", "email", "tel", "url", "search"],
    },
    lang: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    rel: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the relationship between the current document and the linked document.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "alternate", "author", "bookmark", "canonical", "help", "icon", "license", "next", "nofollow", "noreferrer", "prefetch", "prev", "search", "stylesheet", "tag"],
    },
    shape: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "circle", "default", "poly", "rect"],
    },
    spellcheck: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "true", "false"],
    },
    style: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    tabindex: {
      type: {
        name: "number",
        required: false
      },
      defaultValue: 0,
      control: {
        type: "number"
      },
    },
    target: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies where to open the linked document.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "_blank", "_parent", "_self", "_top"],
    },
    title: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    translate: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "yes", "no"],
    },
    type: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the media type of the linked resource.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
  },
  render: ({
    accesskey,
    alt,
    autocapitalize,
    autofocus,
    classProp,
    contenteditable,
    coords,
    data,
    dir,
    download,
    draggable,
    hidden,
    href,
    hreflang,
    id,
    inputmode,
    lang,
    rel,
    shape,
    spellcheck,
    style,
    tabindex,
    target,
    title,
    translate,
    type,
  }) => {
    let el = document.createElement("area");
    if (accesskey) {
      el.setAttribute('accesskey', accesskey);
    }
    if (alt) {
      el.setAttribute('alt', alt);
    }
    if (autocapitalize) {
      el.setAttribute('autocapitalize', autocapitalize);
    }
    if (autofocus) {
      el.setAttribute('autofocus', autofocus);
    }
    if (classProp) {
      el.setAttribute('class', classProp);
    }
    if (contenteditable) {
      el.setAttribute('contenteditable', contenteditable);
    }
    if (coords) {
      el.setAttribute('coords', coords);
    }
    if (data && typeof data === 'object') {
      Object.keys(data).forEach(key => {
        el.setAttribute(`data-${key}`, data[key]);
      });
    }
    if (dir) {
      el.setAttribute('dir', dir);
    }
    if (download) {
      el.setAttribute('download', download);
    }
    if (draggable) {
      el.setAttribute('draggable', draggable);
    }
    if (hidden) {
      el.setAttribute('hidden', hidden);
    }
    if (href) {
      el.setAttribute('href', href);
    }
    if (hreflang) {
      el.setAttribute('hreflang', hreflang);
    }
    if (id) {
      el.setAttribute('id', id);
    }
    if (inputmode) {
      el.setAttribute('inputmode', inputmode);
    }
    if (lang) {
      el.setAttribute('lang', lang);
    }
    if (rel) {
      el.setAttribute('rel', rel);
    }
    if (shape) {
      el.setAttribute('shape', shape);
    }
    if (spellcheck) {
      el.setAttribute('spellcheck', spellcheck);
    }
    if (style) {
      el.setAttribute('style', style);
    }
    if (tabindex) {
      el.setAttribute('tabindex', tabindex);
    }
    if (target) {
      el.setAttribute('target', target);
    }
    if (title) {
      el.setAttribute('title', title);
    }
    if (translate) {
      el.setAttribute('translate', translate);
    }
    if (type) {
      el.setAttribute('type', type);
    }
    return el;
  },
  decorators: [],
};

export const Default = {
  parameters: {
    docs: {
      description: {
        story: 'Default story with all arguments set to default values'
      },
    },
  },
  args: {
    accesskey: "Sample value",
    alt: "Sample value",
    autocapitalize: "",
    autofocus: false,
    classProp: "Sample value",
    contenteditable: "",
    coords: "Sample value",
    data: {},
    dir: "",
    download: "Sample value",
    draggable: false,
    hidden: false,
    href: "Sample value",
    hreflang: "Sample value",
    id: "Sample value",
    inputmode: "",
    lang: "Sample value",
    rel: "",
    shape: "",
    spellcheck: "",
    style: "Sample value",
    tabindex: 0,
    target: "",
    title: "Sample value",
    translate: "",
    type: "Sample value",
  },
};
