/**
 *
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 8, 2025 12:10
 * @component Input
 * @description The input element represents a typed data field, usually with a form control to allow user input.
 */

export default {
  title: "HTML5/Inline Elements/Input",
  tags: ["autodocs"],
  parameters: {
    actions: {
      handles: ['change'],
    },
    layout: "centered",
    componentSubtitle: "Inline Element",
    docs: {
      inlineStories: true,
      source: true,
      description: {
        component: "The input element represents a typed data field, usually with a form control to allow user input.",
      },
    },
  },
  argTypes: {
    accept: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies a comma-separated list of file types that the server accepts.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    accesskey: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    alt: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies alternative text to be displayed when the image cannot be rendered.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaAtomic: {
      type: {
        name: "string",
        required: false
      },
      description: "Indicates whether assistive technologies should present the entire region as a whole when changes occur.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "false", "true"],
    },
    ariaAutocomplete: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies autocomplete behavior for input fields.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "none", "inline", "list", "both"],
    },
    ariaChecked: {
      type: {
        name: "string",
        required: false
      },
      description: "Defines the checked state for checkboxes, radio buttons, or toggle switches.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "false", "true", "mixed", "undefined"],
    },
    ariaControls: {
      type: {
        name: "string",
        required: false
      },
      description: "Identifies the element(s) whose contents or presence are controlled by this element. Value is a list of IDs separated by a space",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaCurrent: {
      type: {
        name: "string",
        required: false
      },
      description: "Indicates the current item within a container or set of related elements.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "false", "page", "step", "location", "date", "time", "true"],
    },
    ariaDescribedby: {
      type: {
        name: "string",
        required: false
      },
      description: "Identifies the element(s) that describes the object. Value is a list of IDs separated by a space",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaDetails: {
      type: {
        name: "string",
        required: false
      },
      description: "References an element that provides additional details about the current element.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaDisabled: {
      type: {
        name: "string",
        required: false
      },
      description: "Indicates that the element is perceivable but disabled, so it is not editable or otherwise operable.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "false", "true"],
    },
    ariaExpanded: {
      type: {
        name: "string",
        required: false
      },
      description: "Indicates whether a collapsible UI element is expanded (true) or collapsed (false).",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "false", "true", "undefined"],
    },
    ariaHaspopup: {
      type: {
        name: "string",
        required: false
      },
      description: "Indicates that an element has an associated popup menu, listbox, tree, grid, or dialog.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "false", "true", "menu", "listbox", "tree", "grid", "dialog"],
    },
    ariaInvalid: {
      type: {
        name: "string",
        required: false
      },
      description: "Indicates that the value entered does not conform to the expected format.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "false", "true", "grammar", "spelling"],
    },
    ariaKeyshortcuts: {
      type: {
        name: "string",
        required: false
      },
      description: "Defines keyboard shortcuts available for the element.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaLabel: {
      type: {
        name: "string",
        required: false
      },
      description: "Defines a string value that labels the current element for assistive technologies.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaLabelledby: {
      type: {
        name: "string",
        required: false
      },
      description: "Identifies the element(s) that labels the current element. Value is a list of IDs separated by a space",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaLive: {
      type: {
        name: "string",
        required: false
      },
      description: "Defines how updates to the element should be announced to screen readers.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "off", "polite", "assertive"],
    },
    ariaPlaceholder: {
      type: {
        name: "string",
        required: false
      },
      description: "Provides a placeholder hint for an input field.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaPressed: {
      type: {
        name: "string",
        required: false
      },
      description: "Indicates whether a toggle button is pressed (true, false, or mixed).",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "false", "true", "mixed", "undefined"],
    },
    ariaReadonly: {
      type: {
        name: "string",
        required: false
      },
      description: "Marks an input field as read-only but still selectable and focusable.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "false", "true"],
    },
    ariaRelevant: {
      type: {
        name: "string",
        required: false
      },
      description: "Indicates what content changes should be announced in a live region.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "additions", "removals", "text", "all", "additions text"],
    },
    ariaRequired: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies that an input field is required before form submission.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "false", "true"],
    },
    ariaRoledescription: {
      type: {
        name: "string",
        required: false
      },
      description: "Provides a human-readable custom role description for assistive technologies.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaValuemax: {
      type: {
        name: "number",
        required: false
      },
      description: "Defines the maximum value for a range input.",
      defaultValue: 0,
      control: {
        type: "number"
      },
    },
    ariaValuemin: {
      type: {
        name: "number",
        required: false
      },
      description: "Defines the minimum value for a range input.",
      defaultValue: 0,
      control: {
        type: "number"
      },
    },
    ariaValuenow: {
      type: {
        name: "number",
        required: false
      },
      description: "Specifies the current value for a range input.",
      defaultValue: 0,
      control: {
        type: "number"
      },
    },
    ariaValuetext: {
      type: {
        name: "string",
        required: false
      },
      description: "Provides a human-readable representation of the current value.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    autocapitalize: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "none", "sentences", "words", "characters"],
    },
    autocomplete: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "off", "on"],
    },
    autocorrect: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies controls whether autocorrection of editable text is enabled for spelling and/or punctuation errors. Default is on.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "off", "on"],
    },
    autofocus: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    checked: {
      type: {
        name: "boolean",
        required: false
      },
      description: "When present, it indicates that an input element should be pre-selected (checked) when the page loads.",
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    classProp: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    contenteditable: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "true", "false", "inherit"],
    },
    data: {
      type: {
        name: "object",
        required: false
      },
      description: "Custom data attributes (data-*). Provide an object with key-value pairs.",
      defaultValue: {},
      control: {
        type: "object"
      },
    },
    dir: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "ltr", "rtl", "auto"],
    },
    dirname: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the direction of the text.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    disabled: {
      type: {
        name: "boolean",
        required: false
      },
      description: "When present, it specifies that an input element should be disabled.",
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    draggable: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    form: {
      type: {
        name: "string",
        required: false
      },
      description: "Associates the button with a form element by ID. Allows buttons to be associated with forms anywhere in the document, not just inside a form element. Can override ancestor form association. Element-specific to button, input, object, select, textarea, and fieldset.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    formaction: {
      type: {
        name: "string",
        required: false
      },
      description: "The URL that processes the form submission. Overrides the action attribute of the button\'s form owner. Only applies to submit buttons. Element-specific to button and input elements with type submit or image.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    formenctype: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies how form data should be encoded when submitting to the server. Only for submit buttons. Overrides the form\'s enctype attribute. Element-specific to button and input elements with type submit or image.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "application/x-www-form-urlencoded", "multipart/form-data", "text/plain"],
    },
    formmethod: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the HTTP method to use when submitting the form. Only for submit buttons. Overrides the form\'s method attribute. Use \"post\" for sensitive data, \"get\" for idempotent operations, \"dialog\" to close dialog without submission. Element-specific to button and input elements with type submit or image.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "get", "post", "dialog"],
    },
    formnovalidate: {
      type: {
        name: "boolean",
        required: false
      },
      description: "When present, specifies that the form should not be validated when submitted. Only applies to submit buttons. Overrides the form\'s novalidate attribute. Element-specific to button and input elements with type submit or image.",
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    formtarget: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies where to display the response after form submission. Can be a browsing context name or keyword (_self, _blank, _parent, _top). Only for submit buttons. Overrides the form\'s target attribute. Element-specific to button and input elements with type submit or image.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "_self", "_blank", "_parent", "_top"],
    },
    height: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the height of the element. The meaning may vary depending on the element type. Accepts integers, pixels (px), and percentages (%).",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    hidden: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    id: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    inputmode: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "none", "text", "decimal", "numeric", "email", "tel", "url", "search"],
    },
    lang: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    list: {
      type: {
        name: "string",
        required: false
      },
      description: "Refers to a <datalist> element that contains pre-defined options for an input element.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    max: {
      type: {
        name: "number",
        required: false
      },
      description: "Specifies the maximum value for an input element, meter, or progress element.",
      defaultValue: 0,
      control: {
        type: "number"
      },
    },
    maxlength: {
      type: {
        name: "number",
        required: false
      },
      description: "Specifies the maximum number of characters allowed in an input field.",
      defaultValue: 0,
      control: {
        type: "number"
      },
    },
    min: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the minimum value for an input element or a meter element.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    minlength: {
      type: {
        name: "number",
        required: false
      },
      description: "Specifies the minimum number of characters required in an input field.",
      defaultValue: 0,
      control: {
        type: "number"
      },
    },
    multiple: {
      type: {
        name: "boolean",
        required: false
      },
      description: "When present, it specifies that the user is allowed to enter more than one value in an input element.",
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    name: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the name associated with the element. The meaning may vary depending on the context.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    pattern: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies a regular expression that the <input> element\'s value is checked against.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    placeholder: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies a short hint that describes the expected value of an input field.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    popovertarget: {
      type: {
        name: "string",
        required: false
      },
      description: "Turns the button into a popover control by specifying the ID of the popover element to control. Creates implicit aria-details and aria-expanded relationships, establishes anchor positioning reference, and improves accessibility. Part of the Popover API. Element-specific to button and input elements.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    popovertargetaction: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the action to perform on the popover element controlled by popovertarget. \"show\" displays a hidden popover, \"hide\" hides a visible popover, \"toggle\" (default) switches between states. Part of the Popover API. Element-specific to button and input elements.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "show", "hide", "toggle"],
    },
    readonly: {
      type: {
        name: "boolean",
        required: false
      },
      description: "When present, it specifies that an input element is read-only.",
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    required: {
      type: {
        name: "boolean",
        required: false
      },
      description: "When present, it specifies that an input field must be filled out before submitting the form.",
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    role: {
      type: {
        name: "string",
        required: false
      },
      description: "The role attribute is used to define the purpose of an element.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "alert", "application", "article", "banner", "button", "checkbox", "complementary", "contentinfo", "dialog", "form", "grid", "group", "heading", "img", "link", "list", "listbox", "listitem", "main", "menu", "menubar", "menuitem", "navigation", "none", "presentation", "radio", "region", "search", "status", "tab", "tablist", "tabpanel", "textbox", "toolbar", "tooltip"],
    },
    size: {
      type: {
        name: "number",
        required: false
      },
      description: "Specifies the height of a hr element in pixels.",
      defaultValue: 0,
      control: {
        type: "number"
      },
    },
    spellcheck: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "true", "false"],
    },
    src: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the URL of the external resource to be embedded or referenced. Required if input type is image",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    step: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the legal number intervals for an input element.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    style: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    tabindex: {
      type: {
        name: "number",
        required: false
      },
      defaultValue: 0,
      control: {
        type: "number"
      },
    },
    title: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    translate: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "yes", "no"],
    },
    type: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the type of the input. Defaults to text if the attribute is omitted",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "button", "checkbox", "color", "date", "datetime-local", "email", "file", "hidden", "image", "month", "number", "password", "radio", "range", "reset", "search", "submit", "tel", "text", "time", "url", "week"],
    },
    value: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the value associated with the element. The meaning and usage may vary depending on the element type.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    width: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the width of the element. The meaning may vary depending on the element type. Accepts integers, pixels (px), and percentages (%).",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
  },
  render: ({
    accept,
    accesskey,
    alt,
    ariaAtomic,
    ariaAutocomplete,
    ariaChecked,
    ariaControls,
    ariaCurrent,
    ariaDescribedby,
    ariaDetails,
    ariaDisabled,
    ariaExpanded,
    ariaHaspopup,
    ariaInvalid,
    ariaKeyshortcuts,
    ariaLabel,
    ariaLabelledby,
    ariaLive,
    ariaPlaceholder,
    ariaPressed,
    ariaReadonly,
    ariaRelevant,
    ariaRequired,
    ariaRoledescription,
    ariaValuemax,
    ariaValuemin,
    ariaValuenow,
    ariaValuetext,
    autocapitalize,
    autocomplete,
    autocorrect,
    autofocus,
    checked,
    classProp,
    contenteditable,
    data,
    dir,
    dirname,
    disabled,
    draggable,
    form,
    formaction,
    formenctype,
    formmethod,
    formnovalidate,
    formtarget,
    height,
    hidden,
    id,
    inputmode,
    lang,
    list,
    max,
    maxlength,
    min,
    minlength,
    multiple,
    name,
    pattern,
    placeholder,
    popovertarget,
    popovertargetaction,
    readonly,
    required,
    role,
    size,
    spellcheck,
    src,
    step,
    style,
    tabindex,
    title,
    translate,
    type,
    value,
    width,
  }) => {
    let el = document.createElement("input");
    if (accept) {
      el.setAttribute('accept', accept);
    }
    if (accesskey) {
      el.setAttribute('accesskey', accesskey);
    }
    if (alt) {
      el.setAttribute('alt', alt);
    }
    if (ariaAtomic) {
      el.setAttribute('aria-atomic', ariaAtomic);
    }
    if (ariaAutocomplete) {
      el.setAttribute('aria-autocomplete', ariaAutocomplete);
    }
    if (ariaChecked) {
      el.setAttribute('aria-checked', ariaChecked);
    }
    if (ariaControls) {
      el.setAttribute('aria-controls', ariaControls);
    }
    if (ariaCurrent) {
      el.setAttribute('aria-current', ariaCurrent);
    }
    if (ariaDescribedby) {
      el.setAttribute('aria-describedby', ariaDescribedby);
    }
    if (ariaDetails) {
      el.setAttribute('aria-details', ariaDetails);
    }
    if (ariaDisabled) {
      el.setAttribute('aria-disabled', ariaDisabled);
    }
    if (ariaExpanded) {
      el.setAttribute('aria-expanded', ariaExpanded);
    }
    if (ariaHaspopup) {
      el.setAttribute('aria-haspopup', ariaHaspopup);
    }
    if (ariaInvalid) {
      el.setAttribute('aria-invalid', ariaInvalid);
    }
    if (ariaKeyshortcuts) {
      el.setAttribute('aria-keyshortcuts', ariaKeyshortcuts);
    }
    if (ariaLabel) {
      el.setAttribute('aria-label', ariaLabel);
    }
    if (ariaLabelledby) {
      el.setAttribute('aria-labelledby', ariaLabelledby);
    }
    if (ariaLive) {
      el.setAttribute('aria-live', ariaLive);
    }
    if (ariaPlaceholder) {
      el.setAttribute('aria-placeholder', ariaPlaceholder);
    }
    if (ariaPressed) {
      el.setAttribute('aria-pressed', ariaPressed);
    }
    if (ariaReadonly) {
      el.setAttribute('aria-readonly', ariaReadonly);
    }
    if (ariaRelevant) {
      el.setAttribute('aria-relevant', ariaRelevant);
    }
    if (ariaRequired) {
      el.setAttribute('aria-required', ariaRequired);
    }
    if (ariaRoledescription) {
      el.setAttribute('aria-roledescription', ariaRoledescription);
    }
    if (ariaValuemax) {
      el.setAttribute('aria-valuemax', ariaValuemax);
    }
    if (ariaValuemin) {
      el.setAttribute('aria-valuemin', ariaValuemin);
    }
    if (ariaValuenow) {
      el.setAttribute('aria-valuenow', ariaValuenow);
    }
    if (ariaValuetext) {
      el.setAttribute('aria-valuetext', ariaValuetext);
    }
    if (autocapitalize) {
      el.setAttribute('autocapitalize', autocapitalize);
    }
    if (autocomplete) {
      el.setAttribute('autocomplete', autocomplete);
    }
    if (autocorrect) {
      el.setAttribute('autocorrect', autocorrect);
    }
    if (autofocus) {
      el.setAttribute('autofocus', autofocus);
    }
    if (checked) {
      el.setAttribute('checked', checked);
    }
    if (classProp) {
      el.setAttribute('class', classProp);
    }
    if (contenteditable) {
      el.setAttribute('contenteditable', contenteditable);
    }
    if (data && typeof data === 'object') {
      Object.keys(data).forEach(key => {
        el.setAttribute(`data-${key}`, data[key]);
      });
    }
    if (dir) {
      el.setAttribute('dir', dir);
    }
    if (dirname) {
      el.setAttribute('dirname', dirname);
    }
    if (disabled) {
      el.setAttribute('disabled', disabled);
    }
    if (draggable) {
      el.setAttribute('draggable', draggable);
    }
    if (form) {
      el.setAttribute('form', form);
    }
    if (formaction) {
      el.setAttribute('formaction', formaction);
    }
    if (formenctype) {
      el.setAttribute('formenctype', formenctype);
    }
    if (formmethod) {
      el.setAttribute('formmethod', formmethod);
    }
    if (formnovalidate) {
      el.setAttribute('formnovalidate', formnovalidate);
    }
    if (formtarget) {
      el.setAttribute('formtarget', formtarget);
    }
    if (height) {
      el.setAttribute('height', height);
    }
    if (hidden) {
      el.setAttribute('hidden', hidden);
    }
    if (id) {
      el.setAttribute('id', id);
    }
    if (inputmode) {
      el.setAttribute('inputmode', inputmode);
    }
    if (lang) {
      el.setAttribute('lang', lang);
    }
    if (list) {
      el.setAttribute('list', list);
    }
    if (max) {
      el.setAttribute('max', max);
    }
    if (maxlength) {
      el.setAttribute('maxlength', maxlength);
    }
    if (min) {
      el.setAttribute('min', min);
    }
    if (minlength) {
      el.setAttribute('minlength', minlength);
    }
    if (multiple) {
      el.setAttribute('multiple', multiple);
    }
    if (name) {
      el.setAttribute('name', name);
    }
    if (pattern) {
      el.setAttribute('pattern', pattern);
    }
    if (placeholder) {
      el.setAttribute('placeholder', placeholder);
    }
    if (popovertarget) {
      el.setAttribute('popovertarget', popovertarget);
    }
    if (popovertargetaction) {
      el.setAttribute('popovertargetaction', popovertargetaction);
    }
    if (readonly) {
      el.setAttribute('readonly', readonly);
    }
    if (required) {
      el.setAttribute('required', required);
    }
    if (role) {
      el.setAttribute('role', role);
    }
    if (size) {
      el.setAttribute('size', size);
    }
    if (spellcheck) {
      el.setAttribute('spellcheck', spellcheck);
    }
    if (src) {
      el.setAttribute('src', src);
    }
    if (step) {
      el.setAttribute('step', step);
    }
    if (style) {
      el.setAttribute('style', style);
    }
    if (tabindex) {
      el.setAttribute('tabindex', tabindex);
    }
    if (title) {
      el.setAttribute('title', title);
    }
    if (translate) {
      el.setAttribute('translate', translate);
    }
    if (type) {
      el.setAttribute('type', type);
    }
    if (value) {
      el.setAttribute('value', value);
    }
    if (width) {
      el.setAttribute('width', width);
    }
    return el;
  },
  decorators: [],
};

export const Default = {
  parameters: {
    docs: {
      description: {
        story: 'Default story with all arguments set to default values'
      },
    },
  },
  args: {
    accept: "Sample value",
    accesskey: "Sample value",
    alt: "Sample value",
    ariaAtomic: "",
    ariaAutocomplete: "",
    ariaChecked: "",
    ariaControls: "Sample value",
    ariaCurrent: "",
    ariaDescribedby: "Sample value",
    ariaDetails: "Sample value",
    ariaDisabled: "",
    ariaExpanded: "",
    ariaHaspopup: "",
    ariaInvalid: "",
    ariaKeyshortcuts: "Sample value",
    ariaLabel: "Sample value",
    ariaLabelledby: "Sample value",
    ariaLive: "",
    ariaPlaceholder: "Sample value",
    ariaPressed: "",
    ariaReadonly: "",
    ariaRelevant: "",
    ariaRequired: "",
    ariaRoledescription: "Sample value",
    ariaValuemax: 0,
    ariaValuemin: 0,
    ariaValuenow: 0,
    ariaValuetext: "Sample value",
    autocapitalize: "",
    autocomplete: "",
    autocorrect: "",
    autofocus: false,
    checked: false,
    classProp: "Sample value",
    contenteditable: "",
    data: {},
    dir: "",
    dirname: "Sample value",
    disabled: false,
    draggable: false,
    form: "Sample value",
    formaction: "Sample value",
    formenctype: "",
    formmethod: "",
    formnovalidate: false,
    formtarget: "",
    height: "Sample value",
    hidden: false,
    id: "Sample value",
    inputmode: "",
    lang: "Sample value",
    list: "Sample value",
    max: 0,
    maxlength: 0,
    min: "Sample value",
    minlength: 0,
    multiple: false,
    name: "Sample value",
    pattern: "Sample value",
    placeholder: "Sample value",
    popovertarget: "Sample value",
    popovertargetaction: "",
    readonly: false,
    required: false,
    role: "",
    size: 0,
    spellcheck: "",
    src: "Sample value",
    step: "Sample value",
    style: "Sample value",
    tabindex: 0,
    title: "Sample value",
    translate: "",
    type: "",
    value: "Sample value",
    width: "Sample value",
  },
};
