/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 13, 2025 17:52:38
 * @component Division
 * @description The div element has no special meaning at all. It represents its children. It can be used with the class, lang, and title attributes to mark up semantics common to a group of consecutive elements.
 */

import React from 'react';

export interface DivProps {
  /** The content to display in the element */
  children?: React.ReactNode;
  /** CSS class names */
  className?: string;
  accesskey?: string;
  /** Identifies the currently active child element (e.g., for autocomplete suggestions or composite widgets). */
  ariaActivedescendant?: string;
  /** Indicates whether assistive technologies should present the entire region as a whole when changes occur. */
  ariaAtomic?: 'false' | 'true';
  /** The aria-busy attribute is used to indicate whether an element is currently busy or not. */
  ariaBusy?: 'true' | 'false';
  /** Identifies the element(s) whose contents or presence are controlled by this element. Value is a list of IDs separated by a space */
  ariaControls?: string;
  /** Identifies the element(s) that describes the object. Value is a list of IDs separated by a space */
  ariaDescribedby?: string;
  /** References an element that provides additional details about the current element. */
  ariaDetails?: string;
  /** Indicates whether the element is exposed to an accessibility API. Use with caution on interactive elements. Set to true only on decorative elements such as icons, or when nav isnt visible */
  ariaHidden?: 'false' | 'true';
  /** Defines keyboard shortcuts available for the element. */
  ariaKeyshortcuts?: string;
  /** Defines a string value that labels the current element for assistive technologies. */
  ariaLabel?: string;
  /** Identifies the element(s) that labels the current element. Value is a list of IDs separated by a space */
  ariaLabelledby?: string;
  /** Defines how updates to the element should be announced to screen readers. */
  ariaLive?: 'off' | 'polite' | 'assertive';
  /** Defines whether multiple items can be selected in a listbox, grid, or tree. */
  ariaMultiselectable?: 'false' | 'true';
  /** Specifies whether an element is horizontal or vertical. */
  ariaOrientation?: 'horizontal' | 'vertical' | 'undefined';
  /** Establishes ownership relationships between elements. Value is a space-separated list of IDs. */
  ariaOwns?: string;
  /** Indicates what content changes should be announced in a live region. */
  ariaRelevant?: 'additions' | 'removals' | 'text' | 'all' | 'additions text';
  /** Provides a human-readable custom role description for assistive technologies. */
  ariaRoledescription?: string;
  autocapitalize?: 'none' | 'sentences' | 'words' | 'characters';
  autofocus?: boolean;
  contenteditable?: 'true' | 'false' | 'inherit';
  /** Custom data attributes (data-*) */
  data?: Record<string, string>;
  dir?: 'ltr' | 'rtl' | 'auto';
  draggable?: boolean;
  hidden?: boolean;
  id?: string;
  inputmode?: 'none' | 'text' | 'decimal' | 'numeric' | 'email' | 'tel' | 'url' | 'search';
  lang?: string;
  popover?: 'auto' | 'hint' | 'manual';
  /** The role attribute is used to define the purpose of an element. */
  role?: 'alert' | 'application' | 'article' | 'banner' | 'button' | 'checkbox' | 'complementary' | 'contentinfo' | 'dialog' | 'form' | 'grid' | 'group' | 'heading' | 'img' | 'link' | 'list' | 'listbox' | 'listitem' | 'main' | 'menu' | 'menubar' | 'menuitem' | 'navigation' | 'none' | 'presentation' | 'radio' | 'region' | 'search' | 'status' | 'tab' | 'tablist' | 'tabpanel' | 'textbox' | 'toolbar' | 'tooltip';
  slot?: string;
  spellcheck?: 'true' | 'false';
  style?: React.CSSProperties;
  tabindex?: number;
  title?: string;
  translate?: 'yes' | 'no';
}

/**
 * Division - The div element has no special meaning at all. It represents its children. It can be used with the class, lang, and title attributes to mark up semantics common to a group of consecutive elements.
 */
export const Div: React.FC<DivProps> = (props: DivProps) => {
  const {
    children,
    className,
    accesskey,
    ariaActivedescendant,
    ariaAtomic,
    ariaBusy,
    ariaControls,
    ariaDescribedby,
    ariaDetails,
    ariaHidden,
    ariaKeyshortcuts,
    ariaLabel,
    ariaLabelledby,
    ariaLive,
    ariaMultiselectable,
    ariaOrientation,
    ariaOwns,
    ariaRelevant,
    ariaRoledescription,
    autocapitalize,
    autofocus,
    contenteditable,
    data,
    dir,
    draggable,
    hidden,
    id,
    inputmode,
    lang,
    popover,
    role,
    slot,
    spellcheck,
    style,
    tabindex,
    title,
    translate
  } = props;

  const elementProps: React.HTMLAttributes<HTMLElement> & Record<string, any> = {};

  // Handle data attributes specially
  if (data) {
    Object.entries(data).forEach(([key, value]) => {
      elementProps[`data-${key}`] = value;
    });
  }

  // Convert camelCase to kebab-case for attribute names
  const toKebabCase = (str: string): string => {
    return str.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
  };

  // Props to exclude from automatic mapping
  const excludedProps = new Set(['children', 'data']);

  // Iterate over all props and map them to element attributes
  Object.entries(props).forEach(([key, value]) => {
    if (excludedProps.has(key) || value === undefined) {
      return;
    }

    // Convert camelCase aria/contenteditable/autocapitalize to kebab-case
    const attrName = key.startsWith('aria') || key === 'contenteditable' || key === 'autocapitalize' 
      ? toKebabCase(key)
      : key;

    // Handle boolean props that need explicit conversion
    if (typeof value === 'boolean' && (key === 'autofocus' || key === 'draggable' || key === 'hidden')) {
      elementProps[attrName] = value ? true : false;
    } else {
      elementProps[attrName] = value;
    }
  });

  return React.createElement(
    'div',
    elementProps,
    children
  );
};

Div.displayName = 'Div';
