/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 7, 2025 17:23:45
 * @component Canvas
 * @description The canvas element is used to draw graphics, on the fly, via scripting (usually JavaScript).
 */

import React from 'react';

export interface CanvasProps {
  /** The content to display in the element */
  children?: React.ReactNode;
  /** CSS class names */
  className?: string;
  accesskey?: string;
  /** The aria-busy attribute is used to indicate whether an element is currently busy or not. */
  ariaBusy?: 'true' | 'false';
  /** Identifies the element(s) whose contents or presence are controlled by this element. Value is a list of IDs separated by a space */
  ariaControls?: string;
  /** Indicates whether the element is exposed to an accessibility API. Use with caution on interactive elements. Set to true only on decorative elements such as icons, or when nav isnt visible */
  ariaHidden?: 'false' | 'true';
  autocapitalize?: 'none' | 'sentences' | 'words' | 'characters';
  autofocus?: boolean;
  contenteditable?: 'true' | 'false' | 'inherit';
  /** Custom data attributes (data-*) */
  data?: Record<string, string>;
  dataPlacement?: 'top' | 'left' | 'right' | 'bottom';
  dataTheme?: 'light' | 'dark';
  dataTooltip?: string;
  dir?: 'ltr' | 'rtl' | 'auto';
  draggable?: boolean;
  /** Specifies the height of the element. The meaning may vary depending on the element type. Accepts integers, pixels (px), and percentages (%). */
  height?: string;
  hidden?: boolean;
  id?: string;
  inputmode?: 'none' | 'text' | 'decimal' | 'numeric' | 'email' | 'tel' | 'url' | 'search';
  lang?: string;
  slot?: string;
  spellcheck?: 'true' | 'false';
  style?: React.CSSProperties;
  tabindex?: number;
  title?: string;
  translate?: 'yes' | 'no';
  /** Specifies the width of the element. The meaning may vary depending on the element type. Accepts integers, pixels (px), and percentages (%). */
  width?: string;
}

/**
 * Canvas - The canvas element is used to draw graphics, on the fly, via scripting (usually JavaScript).
 */
export const Canvas: React.FC<CanvasProps> = (props: CanvasProps) => {
  const {
    children,
    className,
    accesskey,
    ariaBusy,
    ariaControls,
    ariaHidden,
    autocapitalize,
    autofocus,
    contenteditable,
    data,
    dataPlacement,
    dataTheme,
    dataTooltip,
    dir,
    draggable,
    height,
    hidden,
    id,
    inputmode,
    lang,
    slot,
    spellcheck,
    style,
    tabindex,
    title,
    translate,
    width
  } = props;

  const elementProps: React.HTMLAttributes<HTMLElement> & Record<string, any> = {};

  if (className) {
    elementProps.className = className;
  }

  if (data) {
    Object.entries(data).forEach(([key, value]) => {
      elementProps[`data-${key}`] = value;
    });
  }

  if (accesskey !== undefined) {
    elementProps['accesskey'] = accesskey;
  }

  if (ariaBusy !== undefined) {
    elementProps['aria-busy'] = ariaBusy;
  }

  if (ariaControls !== undefined) {
    elementProps['aria-controls'] = ariaControls;
  }

  if (ariaHidden !== undefined) {
    elementProps['aria-hidden'] = ariaHidden;
  }

  if (autocapitalize !== undefined) {
    elementProps['autocapitalize'] = autocapitalize;
  }

  if (autofocus !== undefined) {
    elementProps['autofocus'] = autofocus;
  }

  if (contenteditable !== undefined) {
    elementProps['contenteditable'] = contenteditable;
  }

  if (dataPlacement !== undefined) {
    elementProps['data-placement'] = dataPlacement;
  }

  if (dataTheme !== undefined) {
    elementProps['data-theme'] = dataTheme;
  }

  if (dataTooltip !== undefined) {
    elementProps['data-tooltip'] = dataTooltip;
  }

  if (dir !== undefined) {
    elementProps['dir'] = dir;
  }

  if (draggable !== undefined) {
    elementProps['draggable'] = draggable;
  }

  if (height !== undefined) {
    elementProps['height'] = height;
  }

  if (hidden !== undefined) {
    elementProps['hidden'] = hidden;
  }

  if (id !== undefined) {
    elementProps['id'] = id;
  }

  if (inputmode !== undefined) {
    elementProps['inputmode'] = inputmode;
  }

  if (lang !== undefined) {
    elementProps['lang'] = lang;
  }

  if (slot !== undefined) {
    elementProps['slot'] = slot;
  }

  if (spellcheck !== undefined) {
    elementProps['spellcheck'] = spellcheck;
  }

  if (style !== undefined) {
    elementProps['style'] = style;
  }

  if (tabindex !== undefined) {
    elementProps['tabindex'] = tabindex;
  }

  if (title !== undefined) {
    elementProps['title'] = title;
  }

  if (translate !== undefined) {
    elementProps['translate'] = translate;
  }

  if (width !== undefined) {
    elementProps['width'] = width;
  }

  return React.createElement(
    'canvas',
    elementProps,
    children
  );
};

Canvas.displayName = 'Canvas';
