/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 7, 2025 17:23:47
 * @component Form
 * @description The form element represents a section of a document containing interactive controls for submitting information to a web server.
 */

import React from 'react';

export interface FormProps {
  /** The content to display in the element */
  children?: React.ReactNode;
  /** CSS class names */
  className?: string;
  /** Specifies the character encodings that are to be used for form submission. */
  acceptCharset?: string;
  accesskey?: string;
  /** Specifies the URL where the form data should be submitted when the form is submitted. */
  action?: string;
  /** Indicates that the value entered does not conform to the expected format. */
  ariaInvalid?: 'false' | 'true' | 'grammar' | 'spelling';
  /** Defines a string value that labels the current element for assistive technologies. */
  ariaLabel?: 'breadcrumb';
  /** Specifies whether a form or input field should have autocomplete enabled. Default is on. */
  autocomplete?: 'off' | 'on';
  /** Specifies controls whether autocorrection of editable text is enabled for spelling and/or punctuation errors. Default is on. */
  autocorrect?: 'off' | 'on';
  /** Custom data attributes (data-*) */
  data?: Record<string, string>;
  dataPlacement?: 'top' | 'left' | 'right' | 'bottom';
  dataTheme?: 'light' | 'dark';
  dataTooltip?: string;
  dir?: 'ltr' | 'rtl' | 'auto';
  draggable?: boolean;
  /** Specifies how form data should be encoded before sending it to a server. Only used if the method attribute is set to post. Default is application/x-www-form-urlencoded. */
  enctype?: 'application/x-www-form-urlencoded' | 'multipart/form-data' | 'text/plain';
  hidden?: boolean;
  id?: string;
  lang?: string;
  method?: 'get' | 'post';
  /** Specifies the name associated with the element. The meaning may vary depending on the context. */
  name?: string;
  /** When present, it specifies that a form should not be validated when submitted. */
  novalidate?: boolean;
  slot?: string;
  style?: React.CSSProperties;
  tabindex?: number;
  /** Specifies where to open the linked document. */
  target?: '_blank' | '_parent' | '_self' | '_top';
  title?: string;
  translate?: 'yes' | 'no';
}

/**
 * Form - The form element represents a section of a document containing interactive controls for submitting information to a web server.
 */
export const Form: React.FC<FormProps> = (props: FormProps) => {
  const {
    children,
    className,
    acceptCharset,
    accesskey,
    action,
    ariaInvalid,
    ariaLabel,
    autocomplete,
    autocorrect,
    data,
    dataPlacement,
    dataTheme,
    dataTooltip,
    dir,
    draggable,
    enctype,
    hidden,
    id,
    lang,
    method,
    name,
    novalidate,
    slot,
    style,
    tabindex,
    target,
    title,
    translate
  } = props;

  const elementProps: React.HTMLAttributes<HTMLElement> & Record<string, any> = {};

  if (className) {
    elementProps.className = className;
  }

  if (data) {
    Object.entries(data).forEach(([key, value]) => {
      elementProps[`data-${key}`] = value;
    });
  }

  if (acceptCharset !== undefined) {
    elementProps['accept-charset'] = acceptCharset;
  }

  if (accesskey !== undefined) {
    elementProps['accesskey'] = accesskey;
  }

  if (action !== undefined) {
    elementProps['action'] = action;
  }

  if (ariaInvalid !== undefined) {
    elementProps['aria-invalid'] = ariaInvalid;
  }

  if (ariaLabel !== undefined) {
    elementProps['aria-label'] = ariaLabel;
  }

  if (autocomplete !== undefined) {
    elementProps['autocomplete'] = autocomplete;
  }

  if (autocorrect !== undefined) {
    elementProps['autocorrect'] = autocorrect;
  }

  if (dataPlacement !== undefined) {
    elementProps['data-placement'] = dataPlacement;
  }

  if (dataTheme !== undefined) {
    elementProps['data-theme'] = dataTheme;
  }

  if (dataTooltip !== undefined) {
    elementProps['data-tooltip'] = dataTooltip;
  }

  if (dir !== undefined) {
    elementProps['dir'] = dir;
  }

  if (draggable !== undefined) {
    elementProps['draggable'] = draggable;
  }

  if (enctype !== undefined) {
    elementProps['enctype'] = enctype;
  }

  if (hidden !== undefined) {
    elementProps['hidden'] = hidden;
  }

  if (id !== undefined) {
    elementProps['id'] = id;
  }

  if (lang !== undefined) {
    elementProps['lang'] = lang;
  }

  if (method !== undefined) {
    elementProps['method'] = method;
  }

  if (name !== undefined) {
    elementProps['name'] = name;
  }

  if (novalidate !== undefined) {
    elementProps['novalidate'] = novalidate;
  }

  if (slot !== undefined) {
    elementProps['slot'] = slot;
  }

  if (style !== undefined) {
    elementProps['style'] = style;
  }

  if (tabindex !== undefined) {
    elementProps['tabindex'] = tabindex;
  }

  if (target !== undefined) {
    elementProps['target'] = target;
  }

  if (title !== undefined) {
    elementProps['title'] = title;
  }

  if (translate !== undefined) {
    elementProps['translate'] = translate;
  }

  return React.createElement(
    'form',
    elementProps,
    children
  );
};

Form.displayName = 'Form';
