/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 7, 2025 17:23:47
 * @component Table Row
 * @description The tr element represents a row of cells in a table.
 */

import React from 'react';

export interface TrProps {
  /** The content to display in the element */
  children?: React.ReactNode;
  /** CSS class names */
  className?: string;
  accesskey?: string;
  /** Specifies the horizontal alignment of each row cell. The possible enumerated values are left, center, right, justify, and char. When supported, the char value aligns the textual content on the character defined in the char attribute and on offset defined by the charoff attribute. Use the text-align CSS property instead, as this attribute is deprecated. */
  align?: 'left' | 'center' | 'right' | 'justify' | 'char';
  /** The aria-busy attribute is used to indicate whether an element is currently busy or not. */
  ariaBusy?: 'true' | 'false';
  /** Identifies the element(s) whose contents or presence are controlled by this element. Value is a list of IDs separated by a space */
  ariaControls?: string;
  /** Indicates whether the element is exposed to an accessibility API. Use with caution on interactive elements. Set to true only on decorative elements such as icons, or when nav isnt visible */
  ariaHidden?: 'false' | 'true';
  autocapitalize?: 'none' | 'sentences' | 'words' | 'characters';
  autofocus?: boolean;
  /** Defines the background color of each row cell. The value is an HTML color; either a 6-digit hexadecimal RGB code, prefixed by a #, or a color keyword. Other CSS <color> values are not supported. Use the background-color CSS property instead, as this attribute is deprecated. */
  bgcolor?: string;
  /** Specifies the alignment of the content to a character of each row cell. Typical values for this include a period (.) when attempting to align numbers or monetary values. If align is not set to char, this attribute is ignored. */
  char?: string;
  /** Specifies the number of characters to offset the row cell content from the alignment character specified by the char attribute. */
  charoff?: string;
  contenteditable?: 'true' | 'false' | 'inherit';
  /** Custom data attributes (data-*) */
  data?: Record<string, string>;
  dataPlacement?: 'top' | 'left' | 'right' | 'bottom';
  dataTheme?: 'light' | 'dark';
  dataTooltip?: string;
  dir?: 'ltr' | 'rtl' | 'auto';
  draggable?: boolean;
  hidden?: boolean;
  id?: string;
  inputmode?: 'none' | 'text' | 'decimal' | 'numeric' | 'email' | 'tel' | 'url' | 'search';
  lang?: string;
  spellcheck?: 'true' | 'false';
  style?: React.CSSProperties;
  tabindex?: number;
  title?: string;
  translate?: 'yes' | 'no';
  /** Specifies the vertical alignment of each row cell. The possible enumerated values are baseline, bottom, middle, and top. Use the vertical-align CSS property instead, as this attribute is deprecated. */
  valign?: 'baseline' | 'bottom' | 'middle' | 'top';
}

/**
 * Table Row - The tr element represents a row of cells in a table.
 */
export const Tr: React.FC<TrProps> = (props: TrProps) => {
  const {
    children,
    className,
    accesskey,
    align,
    ariaBusy,
    ariaControls,
    ariaHidden,
    autocapitalize,
    autofocus,
    bgcolor,
    char,
    charoff,
    contenteditable,
    data,
    dataPlacement,
    dataTheme,
    dataTooltip,
    dir,
    draggable,
    hidden,
    id,
    inputmode,
    lang,
    spellcheck,
    style,
    tabindex,
    title,
    translate,
    valign
  } = props;

  const elementProps: React.HTMLAttributes<HTMLElement> & Record<string, any> = {};

  if (className) {
    elementProps.className = className;
  }

  if (data) {
    Object.entries(data).forEach(([key, value]) => {
      elementProps[`data-${key}`] = value;
    });
  }

  if (accesskey !== undefined) {
    elementProps['accesskey'] = accesskey;
  }

  if (align !== undefined) {
    elementProps['align'] = align;
  }

  if (ariaBusy !== undefined) {
    elementProps['aria-busy'] = ariaBusy;
  }

  if (ariaControls !== undefined) {
    elementProps['aria-controls'] = ariaControls;
  }

  if (ariaHidden !== undefined) {
    elementProps['aria-hidden'] = ariaHidden;
  }

  if (autocapitalize !== undefined) {
    elementProps['autocapitalize'] = autocapitalize;
  }

  if (autofocus !== undefined) {
    elementProps['autofocus'] = autofocus;
  }

  if (bgcolor !== undefined) {
    elementProps['bgcolor'] = bgcolor;
  }

  if (char !== undefined) {
    elementProps['char'] = char;
  }

  if (charoff !== undefined) {
    elementProps['charoff'] = charoff;
  }

  if (contenteditable !== undefined) {
    elementProps['contenteditable'] = contenteditable;
  }

  if (dataPlacement !== undefined) {
    elementProps['data-placement'] = dataPlacement;
  }

  if (dataTheme !== undefined) {
    elementProps['data-theme'] = dataTheme;
  }

  if (dataTooltip !== undefined) {
    elementProps['data-tooltip'] = dataTooltip;
  }

  if (dir !== undefined) {
    elementProps['dir'] = dir;
  }

  if (draggable !== undefined) {
    elementProps['draggable'] = draggable;
  }

  if (hidden !== undefined) {
    elementProps['hidden'] = hidden;
  }

  if (id !== undefined) {
    elementProps['id'] = id;
  }

  if (inputmode !== undefined) {
    elementProps['inputmode'] = inputmode;
  }

  if (lang !== undefined) {
    elementProps['lang'] = lang;
  }

  if (spellcheck !== undefined) {
    elementProps['spellcheck'] = spellcheck;
  }

  if (style !== undefined) {
    elementProps['style'] = style;
  }

  if (tabindex !== undefined) {
    elementProps['tabindex'] = tabindex;
  }

  if (title !== undefined) {
    elementProps['title'] = title;
  }

  if (translate !== undefined) {
    elementProps['translate'] = translate;
  }

  if (valign !== undefined) {
    elementProps['valign'] = valign;
  }

  return React.createElement(
    'tr',
    elementProps,
    children
  );
};

Tr.displayName = 'Tr';
