/**
 *
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 8, 2025 12:10
 * @component Script
 * @description The script element is used to embed or reference an executable script within an HTML document. Scripts without async or defer attributes, as well as inline scripts, are fetched and executed immediately, before the browser continues to parse the page.
 */

export default {
  title: "HTML5/Void Elements/Script",
  tags: ["autodocs"],
  parameters: {
    actions: {
      handles: ['change'],
    },
    layout: "centered",
    componentSubtitle: "Void Element",
    docs: {
      inlineStories: true,
      source: true,
      description: {
        component: "The script element is used to embed or reference an executable script within an HTML document. Scripts without async or defer attributes, as well as inline scripts, are fetched and executed immediately, before the browser continues to parse the page.",
      },
    },
  },
  argTypes: {
    text: {
      type: {
        name: "string",
        required: true
      },
      description: "The text or HTML to display in the element",
      defaultValue: "Sample text",
      control: {
        type: "text"
      },
    },
    async: {
      type: {
        name: "boolean",
        required: false
      },
      description: "When present, it specifies that the script will be executed asynchronously as soon as it is available.",
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    charset: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the character encoding for the resource.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    classProp: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    crossorigin: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "anonymous", "use-credentials"],
    },
    data: {
      type: {
        name: "object",
        required: false
      },
      description: "Custom data attributes (data-*). Provide an object with key-value pairs.",
      defaultValue: {},
      control: {
        type: "object"
      },
    },
    defer: {
      type: {
        name: "boolean",
        required: false
      },
      description: "When present, it specifies that the script should be executed after the page has been parsed.",
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    hidden: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    id: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    integrity: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the integrity value of a resource.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    lang: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    nonce: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies a cryptographic nonce that can be used in Content Security Policy (CSP) checks.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    referrerpolicy: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the referrer policy for fetches initiated by the element.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "no-referrer", "no-referrer-when-downgrade", "origin", "origin-when-cross-origin", "same-origin", "strict-origin", "strict-origin-when-cross-origin", "unsafe-url"],
    },
    src: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the URL of the external resource to be embedded or referenced.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    title: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    type: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the media type of the linked resource.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "text/javascript", "module"],
    },
  },
  render: ({
    text,
    async,
    charset,
    classProp,
    crossorigin,
    data,
    defer,
    hidden,
    id,
    integrity,
    lang,
    nonce,
    referrerpolicy,
    src,
    title,
    type,
  }) => {
    let el = document.createElement("script");
    el.innerHTML = text;
    if (async) {
      el.setAttribute('async', async);
    }
    if (charset) {
      el.setAttribute('charset', charset);
    }
    if (classProp) {
      el.setAttribute('class', classProp);
    }
    if (crossorigin) {
      el.setAttribute('crossorigin', crossorigin);
    }
    if (data && typeof data === 'object') {
      Object.keys(data).forEach(key => {
        el.setAttribute(`data-${key}`, data[key]);
      });
    }
    if (defer) {
      el.setAttribute('defer', defer);
    }
    if (hidden) {
      el.setAttribute('hidden', hidden);
    }
    if (id) {
      el.setAttribute('id', id);
    }
    if (integrity) {
      el.setAttribute('integrity', integrity);
    }
    if (lang) {
      el.setAttribute('lang', lang);
    }
    if (nonce) {
      el.setAttribute('nonce', nonce);
    }
    if (referrerpolicy) {
      el.setAttribute('referrerpolicy', referrerpolicy);
    }
    if (src) {
      el.setAttribute('src', src);
    }
    if (title) {
      el.setAttribute('title', title);
    }
    if (type) {
      el.setAttribute('type', type);
    }
    return el;
  },
  decorators: [],
};

export const Default = {
  parameters: {
    docs: {
      description: {
        story: 'Default story with all arguments set to default values'
      },
    },
  },
  args: {
    text: "Sample text",
    async: false,
    charset: "Sample value",
    classProp: "Sample value",
    crossorigin: "",
    data: {},
    defer: false,
    hidden: false,
    id: "Sample value",
    integrity: "Sample value",
    lang: "Sample value",
    nonce: "Sample value",
    referrerpolicy: "",
    src: "Sample value",
    title: "Sample value",
    type: "",
  },
};
