/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 13, 2025 17:52:36
 * @component Meter
 * @description The meter element represents a scalar measurement within a known range, or a fractional value.
 */

import React from 'react';

export interface MeterProps {
  /** The content to display in the element */
  children?: React.ReactNode;
  /** CSS class names */
  className?: string;
  accesskey?: string;
  /** Indicates whether assistive technologies should present the entire region as a whole when changes occur. */
  ariaAtomic?: 'false' | 'true';
  /** References an element that provides additional details about the current element. */
  ariaDetails?: string;
  /** Defines keyboard shortcuts available for the element. */
  ariaKeyshortcuts?: string;
  /** Defines how updates to the element should be announced to screen readers. */
  ariaLive?: 'off' | 'polite' | 'assertive';
  /** Indicates what content changes should be announced in a live region. */
  ariaRelevant?: 'additions' | 'removals' | 'text' | 'all' | 'additions text';
  /** Provides a human-readable custom role description for assistive technologies. */
  ariaRoledescription?: string;
  /** Defines the maximum value for a range input. */
  ariaValuemax?: number;
  /** Defines the minimum value for a range input. */
  ariaValuemin?: number;
  /** Specifies the current value for a range input. */
  ariaValuenow?: number;
  /** Provides a human-readable representation of the current value. */
  ariaValuetext?: string;
  autocapitalize?: 'none' | 'sentences' | 'words' | 'characters';
  autofocus?: boolean;
  contenteditable?: 'true' | 'false' | 'inherit';
  /** Custom data attributes (data-*) */
  data?: Record<string, string>;
  dir?: 'ltr' | 'rtl' | 'auto';
  draggable?: boolean;
  hidden?: boolean;
  /** Specifies the high value for a range input or a meter element. */
  high?: string;
  id?: string;
  inputmode?: 'none' | 'text' | 'decimal' | 'numeric' | 'email' | 'tel' | 'url' | 'search';
  lang?: string;
  /** Specifies the low value for a range input. */
  low?: string;
  /** Specifies the maximum value for an input element, meter, or progress element. */
  max?: number;
  /** Specifies the minimum value for an input element or a meter element. */
  min?: string;
  /** Specifies the optimal value for a gauge or progress element. */
  optimum?: string;
  slot?: string;
  spellcheck?: 'true' | 'false';
  style?: React.CSSProperties;
  tabindex?: number;
  title?: string;
  translate?: 'yes' | 'no';
  /** Specifies the value associated with the element. The meaning and usage may vary depending on the element type. */
  value?: string;
}

/**
 * Meter - The meter element represents a scalar measurement within a known range, or a fractional value.
 */
export const Meter: React.FC<MeterProps> = (props: MeterProps) => {
  const {
    children,
    className,
    accesskey,
    ariaAtomic,
    ariaDetails,
    ariaKeyshortcuts,
    ariaLive,
    ariaRelevant,
    ariaRoledescription,
    ariaValuemax,
    ariaValuemin,
    ariaValuenow,
    ariaValuetext,
    autocapitalize,
    autofocus,
    contenteditable,
    data,
    dir,
    draggable,
    hidden,
    high,
    id,
    inputmode,
    lang,
    low,
    max,
    min,
    optimum,
    slot,
    spellcheck,
    style,
    tabindex,
    title,
    translate,
    value
  } = props;

  const elementProps: React.HTMLAttributes<HTMLElement> & Record<string, any> = {};

  // Handle data attributes specially
  if (data) {
    Object.entries(data).forEach(([key, value]) => {
      elementProps[`data-${key}`] = value;
    });
  }

  // Convert camelCase to kebab-case for attribute names
  const toKebabCase = (str: string): string => {
    return str.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
  };

  // Props to exclude from automatic mapping
  const excludedProps = new Set(['children', 'data']);

  // Iterate over all props and map them to element attributes
  Object.entries(props).forEach(([key, value]) => {
    if (excludedProps.has(key) || value === undefined) {
      return;
    }

    // Convert camelCase aria/contenteditable/autocapitalize to kebab-case
    const attrName = key.startsWith('aria') || key === 'contenteditable' || key === 'autocapitalize' 
      ? toKebabCase(key)
      : key;

    // Handle boolean props that need explicit conversion
    if (typeof value === 'boolean' && (key === 'autofocus' || key === 'draggable' || key === 'hidden')) {
      elementProps[attrName] = value ? true : false;
    } else {
      elementProps[attrName] = value;
    }
  });

  return React.createElement(
    'meter',
    elementProps,
    children
  );
};

Meter.displayName = 'Meter';
