/**
 *
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 8, 2025 12:10
 * @component Track
 * @description The track element is used as a child of the media elements—audio and video. It lets you specify timed text tracks (or time-based data), for example to automatically handle subtitles. The tracks are formatted in WebVTT format (.vtt files) — Web Video Text Tracks.
 */

export default {
  title: "HTML5/Void Elements/Track",
  tags: ["autodocs"],
  parameters: {
    actions: {
      handles: ['change'],
    },
    layout: "centered",
    componentSubtitle: "Void Element",
    docs: {
      inlineStories: true,
      source: true,
      description: {
        component: "The track element is used as a child of the media elements—audio and video. It lets you specify timed text tracks (or time-based data), for example to automatically handle subtitles. The tracks are formatted in WebVTT format (.vtt files) — Web Video Text Tracks.",
      },
    },
  },
  argTypes: {
    classProp: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    data: {
      type: {
        name: "object",
        required: false
      },
      description: "Custom data attributes (data-*). Provide an object with key-value pairs.",
      defaultValue: {},
      control: {
        type: "object"
      },
    },
    defaultProp: {
      type: {
        name: "boolean",
        required: false
      },
      description: "Specifies that the track should be enabled by default when the page loads.",
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    hidden: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    id: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    kind: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "captions", "chapters", "descriptions", "metadata", "subtitles"],
    },
    label: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies a label for the associated form control, option group, or option.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    lang: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    src: {
      type: {
        name: "string",
        required: true
      },
      description: "Specifies the URL of the external resource to be embedded or referenced.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    srclang: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the language of the track text data.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    style: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
  },
  render: ({
    classProp,
    data,
    defaultProp,
    hidden,
    id,
    kind,
    label,
    lang,
    src,
    srclang,
    style,
  }) => {
    let el = document.createElement("track");
    if (classProp) {
      el.setAttribute('class', classProp);
    }
    if (data && typeof data === 'object') {
      Object.keys(data).forEach(key => {
        el.setAttribute(`data-${key}`, data[key]);
      });
    }
    if (defaultProp) {
      el.setAttribute('default', defaultProp);
    }
    if (hidden) {
      el.setAttribute('hidden', hidden);
    }
    if (id) {
      el.setAttribute('id', id);
    }
    if (kind) {
      el.setAttribute('kind', kind);
    }
    if (label) {
      el.setAttribute('label', label);
    }
    if (lang) {
      el.setAttribute('lang', lang);
    }
    if (src) {
      el.setAttribute('src', src);
    }
    if (srclang) {
      el.setAttribute('srclang', srclang);
    }
    if (style) {
      el.setAttribute('style', style);
    }
    return el;
  },
  decorators: [],
};

export const Default = {
  parameters: {
    docs: {
      description: {
        story: 'Default story with all arguments set to default values'
      },
    },
  },
  args: {
    classProp: "Sample value",
    data: {},
    defaultProp: false,
    hidden: false,
    id: "Sample value",
    kind: "",
    label: "Sample value",
    lang: "Sample value",
    src: "Sample value",
    srclang: "Sample value",
    style: "Sample value",
  },
};
