/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 13, 2025 17:52:42
 * @component Script
 * @description The script element is used to embed or reference an executable script within an HTML document. Scripts without async or defer attributes, as well as inline scripts, are fetched and executed immediately, before the browser continues to parse the page.
 */

import React from 'react';

export interface ScriptProps {
  /** The content to display in the element */
  children?: React.ReactNode;
  /** CSS class names */
  className?: string;
  /** When present, it specifies that the script will be executed asynchronously as soon as it is available. */
  async?: boolean;
  /** Specifies the character encoding for the resource. */
  charset?: string;
  crossorigin?: 'anonymous' | 'use-credentials';
  /** Custom data attributes (data-*) */
  data?: Record<string, string>;
  /** When present, it specifies that the script should be executed after the page has been parsed. */
  defer?: boolean;
  hidden?: boolean;
  id?: string;
  /** Specifies the integrity value of a resource. */
  integrity?: string;
  lang?: string;
  /** Specifies a cryptographic nonce that can be used in Content Security Policy (CSP) checks. */
  nonce?: string;
  /** Specifies the referrer policy for fetches initiated by the element. */
  referrerpolicy?: 'no-referrer' | 'no-referrer-when-downgrade' | 'origin' | 'origin-when-cross-origin' | 'same-origin' | 'strict-origin' | 'strict-origin-when-cross-origin' | 'unsafe-url';
  /** Specifies the URL of the external resource to be embedded or referenced. */
  src?: string;
  title?: string;
  /** Specifies the media type of the linked resource. */
  type?: 'text/javascript' | 'module';
}

/**
 * Script - The script element is used to embed or reference an executable script within an HTML document. Scripts without async or defer attributes, as well as inline scripts, are fetched and executed immediately, before the browser continues to parse the page.
 */
export const Script: React.FC<ScriptProps> = (props: ScriptProps) => {
  const {
    children,
    className,
    async,
    charset,
    crossorigin,
    data,
    defer,
    hidden,
    id,
    integrity,
    lang,
    nonce,
    referrerpolicy,
    src,
    title,
    type
  } = props;

  const elementProps: React.HTMLAttributes<HTMLElement> & Record<string, any> = {};

  // Handle data attributes specially
  if (data) {
    Object.entries(data).forEach(([key, value]) => {
      elementProps[`data-${key}`] = value;
    });
  }

  // Convert camelCase to kebab-case for attribute names
  const toKebabCase = (str: string): string => {
    return str.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
  };

  // Props to exclude from automatic mapping
  const excludedProps = new Set(['children', 'data']);

  // Iterate over all props and map them to element attributes
  Object.entries(props).forEach(([key, value]) => {
    if (excludedProps.has(key) || value === undefined) {
      return;
    }

    // Convert camelCase aria/contenteditable/autocapitalize to kebab-case
    const attrName = key.startsWith('aria') || key === 'contenteditable' || key === 'autocapitalize' 
      ? toKebabCase(key)
      : key;

    // Handle boolean props that need explicit conversion
    if (typeof value === 'boolean' && (key === 'async' || key === 'defer' || key === 'hidden')) {
      elementProps[attrName] = value ? true : false;
    } else {
      elementProps[attrName] = value;
    }
  });

  return React.createElement(
    'script',
    elementProps,
    children
  );
};

Script.displayName = 'Script';
