/**
 *
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 13, 2025 17:52
 * @component Meta
 * @description The meta element provides metadata about the HTML document. Metadata will not be displayed on the page, but is machine-readable. Mainly used in the head but allowed inside the body if itemprop attribute is set.
 */

export default {
  title: "HTML5/Void Elements/Meta",
  tags: ["autodocs"],
  parameters: {
    actions: {
      handles: ['change'],
    },
    layout: "centered",
    componentSubtitle: "Void Element",
    docs: {
      inlineStories: true,
      source: true,
      description: {
        component: "The meta element provides metadata about the HTML document. Metadata will not be displayed on the page, but is machine-readable. Mainly used in the head but allowed inside the body if itemprop attribute is set.",
      },
    },
  },
  argTypes: {
    charset: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the character encoding for the resource.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    classProp: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    content: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the value associated with the http-equiv or name attribute.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    data: {
      type: {
        name: "object",
        required: false
      },
      description: "Custom data attributes (data-*). Provide an object with key-value pairs.",
      defaultValue: {},
      control: {
        type: "object"
      },
    },
    hidden: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    httpEquiv: {
      type: {
        name: "string",
        required: false
      },
      description: "Provides an HTTP header for the information/value of the content attribute.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "content-language", "content-type", "default-style", "refresh"],
    },
    id: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    lang: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    name: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the name associated with the element. The meaning may vary depending on the context.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    scheme: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the content type of the value attribute when the http-equiv attribute is used.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    title: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
  },
  render: ({
    charset,
    classProp,
    content,
    data,
    hidden,
    httpEquiv,
    id,
    lang,
    name,
    scheme,
    title,
  }) => {
    let el = document.createElement("meta");
    if (charset) {
      el.setAttribute('charset', charset);
    }
    if (classProp) {
      el.setAttribute('class', classProp);
    }
    if (content) {
      el.setAttribute('content', content);
    }
    if (data && typeof data === 'object') {
      Object.keys(data).forEach(key => {
        el.setAttribute(`data-${key}`, data[key]);
      });
    }
    if (hidden) {
      el.setAttribute('hidden', hidden);
    }
    if (httpEquiv) {
      el.setAttribute('http-equiv', httpEquiv);
    }
    if (id) {
      el.setAttribute('id', id);
    }
    if (lang) {
      el.setAttribute('lang', lang);
    }
    if (name) {
      el.setAttribute('name', name);
    }
    if (scheme) {
      el.setAttribute('scheme', scheme);
    }
    if (title) {
      el.setAttribute('title', title);
    }
    return el;
  },
  decorators: [],
};

export const Default = {
  parameters: {
    docs: {
      description: {
        story: 'Default story with all arguments set to default values'
      },
    },
  },
  args: {
    charset: "Sample value",
    classProp: "Sample value",
    content: "Sample value",
    data: {},
    hidden: false,
    httpEquiv: "",
    id: "Sample value",
    lang: "Sample value",
    name: "Sample value",
    scheme: "Sample value",
    title: "Sample value",
  },
};
