/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 13, 2025 17:52:38
 * @component Column Group
 * @description The colgroup element represents a group of one or more columns in the table that is its parent, if it has a parent and that is a table element.
 */

import React from 'react';

export interface ColgroupProps {
  /** The content to display in the element */
  children?: React.ReactNode;
  /** CSS class names */
  className?: string;
  /** Custom data attributes (data-*) */
  data?: Record<string, string>;
  dir?: 'ltr' | 'rtl' | 'auto';
  hidden?: boolean;
  id?: string;
  lang?: string;
  slot?: string;
  /** Specifies the number of columns the <col> element should span in a table. */
  span?: number;
  style?: React.CSSProperties;
}

/**
 * Column Group - The colgroup element represents a group of one or more columns in the table that is its parent, if it has a parent and that is a table element.
 */
export const Colgroup: React.FC<ColgroupProps> = (props: ColgroupProps) => {
  const {
    children,
    className,
    data,
    dir,
    hidden,
    id,
    lang,
    slot,
    span,
    style
  } = props;

  const elementProps: React.HTMLAttributes<HTMLElement> & Record<string, any> = {};

  // Handle data attributes specially
  if (data) {
    Object.entries(data).forEach(([key, value]) => {
      elementProps[`data-${key}`] = value;
    });
  }

  // Convert camelCase to kebab-case for attribute names
  const toKebabCase = (str: string): string => {
    return str.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
  };

  // Props to exclude from automatic mapping
  const excludedProps = new Set(['children', 'data']);

  // Iterate over all props and map them to element attributes
  Object.entries(props).forEach(([key, value]) => {
    if (excludedProps.has(key) || value === undefined) {
      return;
    }

    // Convert camelCase aria/contenteditable/autocapitalize to kebab-case
    const attrName = key.startsWith('aria') || key === 'contenteditable' || key === 'autocapitalize' 
      ? toKebabCase(key)
      : key;

    // Handle boolean props that need explicit conversion
    if (typeof value === 'boolean' && (key === 'hidden')) {
      elementProps[attrName] = value ? true : false;
    } else {
      elementProps[attrName] = value;
    }
  });

  return React.createElement(
    'colgroup',
    elementProps,
    children
  );
};

Colgroup.displayName = 'Colgroup';
