/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 7, 2025 17:23:41
 * @component Button
 * @description The button element represents a clickable button, used to submit forms or anywhere in a document for accessible, standard button functionality.
 */

import React from 'react';

export interface ButtonProps {
  /** The content to display in the element */
  children?: React.ReactNode;
  /** CSS class names */
  className?: string;
  accesskey?: string;
  /** The aria-busy attribute is used to indicate whether an element is currently busy or not. */
  ariaBusy?: 'true' | 'false';
  /** Identifies the element(s) whose contents or presence are controlled by this element. Value is a list of IDs separated by a space */
  ariaControls?: string;
  /** Indicates the current item within a container or set of related elements. */
  ariaCurrent?: 'false' | 'page' | 'step' | 'location' | 'date' | 'time' | 'true';
  /** Indicates that the element is perceivable but disabled, so it is not editable or otherwise operable. */
  ariaDisabled?: 'false' | 'true';
  /** Defines a string value that labels the current element for assistive technologies. */
  ariaLabel?: 'breadcrumb';
  autocapitalize?: 'none' | 'sentences' | 'words' | 'characters';
  /** Specifies controls whether autocorrection of editable text is enabled for spelling and/or punctuation errors. Default is on. */
  autocorrect?: 'off' | 'on';
  /** When present, it specifies that an element should automatically get focus when the page loads. */
  autofocus?: boolean;
  /** Specifies the action to be performed on an element controlled via commandfor attribute. Supports dialog operations (show-modal, close, request-close), popover operations (show-popover, hide-popover, toggle-popover), and custom commands prefixed with "--". Provides declarative element control without JavaScript. Element-specific to button element. */
  command?: string;
  /** Turns the button into a command button by specifying the ID of the element to control. Works with the command attribute to define the action. A more general version of popovertarget. Enables declarative control of interactive elements. Element-specific to button element. */
  commandfor?: string;
  contenteditable?: 'true' | 'false' | 'inherit';
  /** Custom data attributes (data-*) */
  data?: Record<string, string>;
  dataPlacement?: 'top' | 'left' | 'right' | 'bottom';
  dataTheme?: 'light' | 'dark';
  dataTooltip?: string;
  dir?: 'ltr' | 'rtl' | 'auto';
  /** When present, it specifies that an input element should be disabled. */
  disabled?: boolean;
  draggable?: boolean;
  /** Associates the button with a form element by ID. Allows buttons to be associated with forms anywhere in the document, not just inside a form element. Can override ancestor form association. Element-specific to button, input, object, select, textarea, and fieldset. */
  form?: string;
  /** The URL that processes the form submission. Overrides the action attribute of the button's form owner. Only applies to submit buttons. Element-specific to button and input elements with type submit or image. */
  formaction?: string;
  /** Specifies how form data should be encoded when submitting to the server. Only for submit buttons. Overrides the form's enctype attribute. Element-specific to button and input elements with type submit or image. */
  formenctype?: 'application/x-www-form-urlencoded' | 'multipart/form-data' | 'text/plain';
  /** Specifies the HTTP method to use when submitting the form. Only for submit buttons. Overrides the form's method attribute. Use "post" for sensitive data, "get" for idempotent operations, "dialog" to close dialog without submission. Element-specific to button and input elements with type submit or image. */
  formmethod?: 'get' | 'post' | 'dialog';
  /** When present, specifies that the form should not be validated when submitted. Only applies to submit buttons. Overrides the form's novalidate attribute. Element-specific to button and input elements with type submit or image. */
  formnovalidate?: boolean;
  /** Specifies where to display the response after form submission. Can be a browsing context name or keyword (_self, _blank, _parent, _top). Only for submit buttons. Overrides the form's target attribute. Element-specific to button and input elements with type submit or image. */
  formtarget?: '_self' | '_blank' | '_parent' | '_top' | string;
  hidden?: boolean;
  id?: string;
  inputmode?: 'none' | 'text' | 'decimal' | 'numeric' | 'email' | 'tel' | 'url' | 'search';
  lang?: string;
  /** Specifies the name associated with the element. The meaning may vary depending on the context. */
  name?: string;
  /** Turns the button into a popover control by specifying the ID of the popover element to control. Creates implicit aria-details and aria-expanded relationships, establishes anchor positioning reference, and improves accessibility. Part of the Popover API. Element-specific to button and input elements. */
  popovertarget?: string;
  /** Specifies the action to perform on the popover element controlled by popovertarget. "show" displays a hidden popover, "hide" hides a visible popover, "toggle" (default) switches between states. Part of the Popover API. Element-specific to button and input elements. */
  popovertargetaction?: 'show' | 'hide' | 'toggle';
  /** Defines the semantic purpose of an element for assistive technologies. */
  role?: 'button';
  slot?: string;
  spellcheck?: 'true' | 'false';
  style?: React.CSSProperties;
  tabindex?: number;
  title?: string;
  translate?: 'yes' | 'no';
  /** Specifies the type of the button. */
  type?: 'submit' | 'reset' | 'button';
  /** Specifies the value associated with the element. The meaning and usage may vary depending on the element type. */
  value?: string;
}

/**
 * Button - The button element represents a clickable button, used to submit forms or anywhere in a document for accessible, standard button functionality.
 */
export const Button: React.FC<ButtonProps> = (props: ButtonProps) => {
  const {
    children,
    className,
    accesskey,
    ariaBusy,
    ariaControls,
    ariaCurrent,
    ariaDisabled,
    ariaLabel,
    autocapitalize,
    autocorrect,
    autofocus,
    command,
    commandfor,
    contenteditable,
    data,
    dataPlacement,
    dataTheme,
    dataTooltip,
    dir,
    disabled,
    draggable,
    form,
    formaction,
    formenctype,
    formmethod,
    formnovalidate,
    formtarget,
    hidden,
    id,
    inputmode,
    lang,
    name,
    popovertarget,
    popovertargetaction,
    role,
    slot,
    spellcheck,
    style,
    tabindex,
    title,
    translate,
    type,
    value
  } = props;

  const elementProps: React.HTMLAttributes<HTMLElement> & Record<string, any> = {};

  if (className) {
    elementProps.className = className;
  }

  if (data) {
    Object.entries(data).forEach(([key, value]) => {
      elementProps[`data-${key}`] = value;
    });
  }

  if (accesskey !== undefined) {
    elementProps['accesskey'] = accesskey;
  }

  if (ariaBusy !== undefined) {
    elementProps['aria-busy'] = ariaBusy;
  }

  if (ariaControls !== undefined) {
    elementProps['aria-controls'] = ariaControls;
  }

  if (ariaCurrent !== undefined) {
    elementProps['aria-current'] = ariaCurrent;
  }

  if (ariaDisabled !== undefined) {
    elementProps['aria-disabled'] = ariaDisabled;
  }

  if (ariaLabel !== undefined) {
    elementProps['aria-label'] = ariaLabel;
  }

  if (autocapitalize !== undefined) {
    elementProps['autocapitalize'] = autocapitalize;
  }

  if (autocorrect !== undefined) {
    elementProps['autocorrect'] = autocorrect;
  }

  if (autofocus !== undefined) {
    elementProps['autofocus'] = autofocus;
  }

  if (command !== undefined) {
    elementProps['command'] = command;
  }

  if (commandfor !== undefined) {
    elementProps['commandfor'] = commandfor;
  }

  if (contenteditable !== undefined) {
    elementProps['contenteditable'] = contenteditable;
  }

  if (dataPlacement !== undefined) {
    elementProps['data-placement'] = dataPlacement;
  }

  if (dataTheme !== undefined) {
    elementProps['data-theme'] = dataTheme;
  }

  if (dataTooltip !== undefined) {
    elementProps['data-tooltip'] = dataTooltip;
  }

  if (dir !== undefined) {
    elementProps['dir'] = dir;
  }

  if (disabled !== undefined) {
    elementProps['disabled'] = disabled;
  }

  if (draggable !== undefined) {
    elementProps['draggable'] = draggable;
  }

  if (form !== undefined) {
    elementProps['form'] = form;
  }

  if (formaction !== undefined) {
    elementProps['formaction'] = formaction;
  }

  if (formenctype !== undefined) {
    elementProps['formenctype'] = formenctype;
  }

  if (formmethod !== undefined) {
    elementProps['formmethod'] = formmethod;
  }

  if (formnovalidate !== undefined) {
    elementProps['formnovalidate'] = formnovalidate;
  }

  if (formtarget !== undefined) {
    elementProps['formtarget'] = formtarget;
  }

  if (hidden !== undefined) {
    elementProps['hidden'] = hidden;
  }

  if (id !== undefined) {
    elementProps['id'] = id;
  }

  if (inputmode !== undefined) {
    elementProps['inputmode'] = inputmode;
  }

  if (lang !== undefined) {
    elementProps['lang'] = lang;
  }

  if (name !== undefined) {
    elementProps['name'] = name;
  }

  if (popovertarget !== undefined) {
    elementProps['popovertarget'] = popovertarget;
  }

  if (popovertargetaction !== undefined) {
    elementProps['popovertargetaction'] = popovertargetaction;
  }

  if (role !== undefined) {
    elementProps['role'] = role;
  }

  if (slot !== undefined) {
    elementProps['slot'] = slot;
  }

  if (spellcheck !== undefined) {
    elementProps['spellcheck'] = spellcheck;
  }

  if (style !== undefined) {
    elementProps['style'] = style;
  }

  if (tabindex !== undefined) {
    elementProps['tabindex'] = tabindex;
  }

  if (title !== undefined) {
    elementProps['title'] = title;
  }

  if (translate !== undefined) {
    elementProps['translate'] = translate;
  }

  if (type !== undefined) {
    elementProps['type'] = type;
  }

  if (value !== undefined) {
    elementProps['value'] = value;
  }

  return React.createElement(
    'button',
    elementProps,
    children
  );
};

Button.displayName = 'Button';
