/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 7, 2025 17:23:41
 * @component Image
 * @description The img element represents an image.
 */

import React from 'react';

export interface ImgProps {
  /** CSS class names */
  className?: string;
  /** Specifies alternative text to be displayed when the image cannot be rendered. */
  alt: string;
  /** Indicates whether the element is exposed to an accessibility API. Use with caution on interactive elements. Set to true only on decorative elements such as icons, or when nav isnt visible */
  ariaHidden?: 'false' | 'true';
  /** Defines a string value that labels the current element for assistive technologies. */
  ariaLabel?: 'breadcrumb';
  crossorigin?: 'anonymous' | 'use-credentials';
  /** Custom data attributes (data-*) */
  data?: Record<string, string>;
  dataPlacement?: 'top' | 'left' | 'right' | 'bottom';
  dataTheme?: 'light' | 'dark';
  dataTooltip?: string;
  /** Specifies the decoding process applied to the image. */
  decoding?: 'async' | 'auto' | 'sync';
  dir?: 'ltr' | 'rtl' | 'auto';
  draggable?: boolean;
  /** Specifies the height of the element. The meaning may vary depending on the element type. Accepts integers, pixels (px), and percentages (%). */
  height?: string;
  hidden?: boolean;
  id?: string;
  /** Specifies that an area should be part of an image map. */
  ismap?: boolean;
  lang?: string;
  /** Specifies the referrer policy for fetches initiated by the element. */
  referrerpolicy?: 'no-referrer' | 'no-referrer-when-downgrade' | 'origin' | 'origin-when-cross-origin' | 'same-origin' | 'strict-origin' | 'strict-origin-when-cross-origin' | 'unsafe-url';
  /** Specifies the sizes of the images or icons for different display/window sizes. */
  sizes?: string;
  /** Specifies the URL of the external resource to be embedded or referenced. */
  src: string;
  /** Specifies a set of image candidate URLs and descriptors for responsive images. */
  srcset?: string;
  style?: React.CSSProperties;
  tabindex?: number;
  title?: string;
  /** Specifies a client-side image map to be used with the element. */
  usemap?: string;
  /** Specifies the width of the element. The meaning may vary depending on the element type. Accepts integers, pixels (px), and percentages (%). */
  width?: string;
}

/**
 * Image - The img element represents an image.
 */
export const Img: React.FC<ImgProps> = (props: ImgProps) => {
  const {
    className,
    alt,
    ariaHidden,
    ariaLabel,
    crossorigin,
    data,
    dataPlacement,
    dataTheme,
    dataTooltip,
    decoding,
    dir,
    draggable,
    height,
    hidden,
    id,
    ismap,
    lang,
    referrerpolicy,
    sizes,
    src,
    srcset,
    style,
    tabindex,
    title,
    usemap,
    width
  } = props;

  const elementProps: React.HTMLAttributes<HTMLElement> & Record<string, any> = {};

  if (className) {
    elementProps.className = className;
  }

  if (data) {
    Object.entries(data).forEach(([key, value]) => {
      elementProps[`data-${key}`] = value;
    });
  }

  if (alt !== undefined) {
    elementProps['alt'] = alt;
  }

  if (ariaHidden !== undefined) {
    elementProps['aria-hidden'] = ariaHidden;
  }

  if (ariaLabel !== undefined) {
    elementProps['aria-label'] = ariaLabel;
  }

  if (crossorigin !== undefined) {
    elementProps['crossorigin'] = crossorigin;
  }

  if (dataPlacement !== undefined) {
    elementProps['data-placement'] = dataPlacement;
  }

  if (dataTheme !== undefined) {
    elementProps['data-theme'] = dataTheme;
  }

  if (dataTooltip !== undefined) {
    elementProps['data-tooltip'] = dataTooltip;
  }

  if (decoding !== undefined) {
    elementProps['decoding'] = decoding;
  }

  if (dir !== undefined) {
    elementProps['dir'] = dir;
  }

  if (draggable !== undefined) {
    elementProps['draggable'] = draggable;
  }

  if (height !== undefined) {
    elementProps['height'] = height;
  }

  if (hidden !== undefined) {
    elementProps['hidden'] = hidden;
  }

  if (id !== undefined) {
    elementProps['id'] = id;
  }

  if (ismap !== undefined) {
    elementProps['ismap'] = ismap;
  }

  if (lang !== undefined) {
    elementProps['lang'] = lang;
  }

  if (referrerpolicy !== undefined) {
    elementProps['referrerpolicy'] = referrerpolicy;
  }

  if (sizes !== undefined) {
    elementProps['sizes'] = sizes;
  }

  if (src !== undefined) {
    elementProps['src'] = src;
  }

  if (srcset !== undefined) {
    elementProps['srcset'] = srcset;
  }

  if (style !== undefined) {
    elementProps['style'] = style;
  }

  if (tabindex !== undefined) {
    elementProps['tabindex'] = tabindex;
  }

  if (title !== undefined) {
    elementProps['title'] = title;
  }

  if (usemap !== undefined) {
    elementProps['usemap'] = usemap;
  }

  if (width !== undefined) {
    elementProps['width'] = width;
  }

  return React.createElement(
    'img',
    elementProps
  );
};

Img.displayName = 'Img';
