/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 7, 2025 17:23:41
 * @component Input
 * @description The input element represents a typed data field, usually with a form control to allow user input.
 */

import React from 'react';

export interface InputProps {
  /** CSS class names */
  className?: string;
  /** Specifies a comma-separated list of file types that the server accepts. */
  accept?: string;
  accesskey?: string;
  /** Specifies alternative text to be displayed when the image cannot be rendered. */
  alt?: string;
  /** Identifies the element(s) whose contents or presence are controlled by this element. Value is a list of IDs separated by a space */
  ariaControls?: string;
  /** Indicates the current item within a container or set of related elements. */
  ariaCurrent?: 'false' | 'page' | 'step' | 'location' | 'date' | 'time' | 'true';
  /** Indicates that the element is perceivable but disabled, so it is not editable or otherwise operable. */
  ariaDisabled?: 'false' | 'true';
  /** Indicates that the value entered does not conform to the expected format. */
  ariaInvalid?: 'false' | 'true' | 'grammar' | 'spelling';
  /** Defines a string value that labels the current element for assistive technologies. */
  ariaLabel?: 'breadcrumb';
  autocapitalize?: 'none' | 'sentences' | 'words' | 'characters';
  autocomplete?: 'off' | 'on';
  /** Specifies controls whether autocorrection of editable text is enabled for spelling and/or punctuation errors. Default is on. */
  autocorrect?: 'off' | 'on';
  autofocus?: boolean;
  /** When present, it indicates that an input element should be pre-selected (checked) when the page loads. */
  checked?: boolean;
  contenteditable?: 'true' | 'false' | 'inherit';
  /** Custom data attributes (data-*) */
  data?: Record<string, string>;
  dataPlacement?: 'top' | 'left' | 'right' | 'bottom';
  dataTheme?: 'light' | 'dark';
  dataTooltip?: string;
  dir?: 'ltr' | 'rtl' | 'auto';
  /** Specifies the direction of the text. */
  dirname?: string;
  /** When present, it specifies that an input element should be disabled. */
  disabled?: boolean;
  draggable?: boolean;
  /** Associates the button with a form element by ID. Allows buttons to be associated with forms anywhere in the document, not just inside a form element. Can override ancestor form association. Element-specific to button, input, object, select, textarea, and fieldset. */
  form?: string;
  /** The URL that processes the form submission. Overrides the action attribute of the button's form owner. Only applies to submit buttons. Element-specific to button and input elements with type submit or image. */
  formaction?: string;
  /** Specifies how form data should be encoded when submitting to the server. Only for submit buttons. Overrides the form's enctype attribute. Element-specific to button and input elements with type submit or image. */
  formenctype?: 'application/x-www-form-urlencoded' | 'multipart/form-data' | 'text/plain';
  /** Specifies the HTTP method to use when submitting the form. Only for submit buttons. Overrides the form's method attribute. Use "post" for sensitive data, "get" for idempotent operations, "dialog" to close dialog without submission. Element-specific to button and input elements with type submit or image. */
  formmethod?: 'get' | 'post' | 'dialog';
  /** When present, specifies that the form should not be validated when submitted. Only applies to submit buttons. Overrides the form's novalidate attribute. Element-specific to button and input elements with type submit or image. */
  formnovalidate?: boolean;
  /** Specifies where to display the response after form submission. Can be a browsing context name or keyword (_self, _blank, _parent, _top). Only for submit buttons. Overrides the form's target attribute. Element-specific to button and input elements with type submit or image. */
  formtarget?: '_self' | '_blank' | '_parent' | '_top' | string;
  /** Specifies the height of the element. The meaning may vary depending on the element type. Accepts integers, pixels (px), and percentages (%). */
  height?: string;
  hidden?: boolean;
  id?: string;
  inputmode?: 'none' | 'text' | 'decimal' | 'numeric' | 'email' | 'tel' | 'url' | 'search';
  lang?: string;
  /** Refers to a <datalist> element that contains pre-defined options for an input element. */
  list?: string;
  /** Specifies the maximum value for an input element, meter, or progress element. */
  max?: number;
  /** Specifies the maximum number of characters allowed in an input field. */
  maxlength?: number;
  /** Specifies the minimum value for an input element or a meter element. */
  min?: string;
  /** Specifies the minimum number of characters required in an input field. */
  minlength?: number;
  /** When present, it specifies that the user is allowed to enter more than one value in an input element. */
  multiple?: boolean;
  /** Specifies the name associated with the element. The meaning may vary depending on the context. */
  name?: string;
  /** Specifies a regular expression that the <input> element's value is checked against. */
  pattern?: string;
  /** Specifies a short hint that describes the expected value of an input field. */
  placeholder?: string;
  /** Turns the button into a popover control by specifying the ID of the popover element to control. Creates implicit aria-details and aria-expanded relationships, establishes anchor positioning reference, and improves accessibility. Part of the Popover API. Element-specific to button and input elements. */
  popovertarget?: string;
  /** Specifies the action to perform on the popover element controlled by popovertarget. "show" displays a hidden popover, "hide" hides a visible popover, "toggle" (default) switches between states. Part of the Popover API. Element-specific to button and input elements. */
  popovertargetaction?: 'show' | 'hide' | 'toggle';
  /** When present, it specifies that an input element is read-only. */
  readonly?: boolean;
  /** When present, it specifies that an input field must be filled out before submitting the form. */
  required?: boolean;
  /** The role attribute is used to define the purpose of an element. */
  role?: 'search';
  /** Specifies the height of a hr element in pixels. */
  size?: number;
  spellcheck?: 'true' | 'false';
  /** Specifies the URL of the external resource to be embedded or referenced. Required if input type is image */
  src?: string;
  /** Specifies the legal number intervals for an input element. */
  step?: string;
  style?: React.CSSProperties;
  tabindex?: number;
  title?: string;
  translate?: 'yes' | 'no';
  /** Specifies the type of the input. Defaults to text if the attribute is omitted */
  type?: 'button' | 'checkbox' | 'color' | 'date' | 'datetime-local' | 'email' | 'file' | 'hidden' | 'image' | 'month' | 'number' | 'password' | 'radio' | 'range' | 'reset' | 'search' | 'submit' | 'tel' | 'text' | 'time' | 'url' | 'week';
  /** Specifies the value associated with the element. The meaning and usage may vary depending on the element type. */
  value?: string;
  /** Specifies the width of the element. The meaning may vary depending on the element type. Accepts integers, pixels (px), and percentages (%). */
  width?: string;
}

/**
 * Input - The input element represents a typed data field, usually with a form control to allow user input.
 */
export const Input: React.FC<InputProps> = (props: InputProps) => {
  const {
    className,
    accept,
    accesskey,
    alt,
    ariaControls,
    ariaCurrent,
    ariaDisabled,
    ariaInvalid,
    ariaLabel,
    autocapitalize,
    autocomplete,
    autocorrect,
    autofocus,
    checked,
    contenteditable,
    data,
    dataPlacement,
    dataTheme,
    dataTooltip,
    dir,
    dirname,
    disabled,
    draggable,
    form,
    formaction,
    formenctype,
    formmethod,
    formnovalidate,
    formtarget,
    height,
    hidden,
    id,
    inputmode,
    lang,
    list,
    max,
    maxlength,
    min,
    minlength,
    multiple,
    name,
    pattern,
    placeholder,
    popovertarget,
    popovertargetaction,
    readonly,
    required,
    role,
    size,
    spellcheck,
    src,
    step,
    style,
    tabindex,
    title,
    translate,
    type,
    value,
    width
  } = props;

  const elementProps: React.HTMLAttributes<HTMLElement> & Record<string, any> = {};

  if (className) {
    elementProps.className = className;
  }

  if (data) {
    Object.entries(data).forEach(([key, value]) => {
      elementProps[`data-${key}`] = value;
    });
  }

  if (accept !== undefined) {
    elementProps['accept'] = accept;
  }

  if (accesskey !== undefined) {
    elementProps['accesskey'] = accesskey;
  }

  if (alt !== undefined) {
    elementProps['alt'] = alt;
  }

  if (ariaControls !== undefined) {
    elementProps['aria-controls'] = ariaControls;
  }

  if (ariaCurrent !== undefined) {
    elementProps['aria-current'] = ariaCurrent;
  }

  if (ariaDisabled !== undefined) {
    elementProps['aria-disabled'] = ariaDisabled;
  }

  if (ariaInvalid !== undefined) {
    elementProps['aria-invalid'] = ariaInvalid;
  }

  if (ariaLabel !== undefined) {
    elementProps['aria-label'] = ariaLabel;
  }

  if (autocapitalize !== undefined) {
    elementProps['autocapitalize'] = autocapitalize;
  }

  if (autocomplete !== undefined) {
    elementProps['autocomplete'] = autocomplete;
  }

  if (autocorrect !== undefined) {
    elementProps['autocorrect'] = autocorrect;
  }

  if (autofocus !== undefined) {
    elementProps['autofocus'] = autofocus;
  }

  if (checked !== undefined) {
    elementProps['checked'] = checked;
  }

  if (contenteditable !== undefined) {
    elementProps['contenteditable'] = contenteditable;
  }

  if (dataPlacement !== undefined) {
    elementProps['data-placement'] = dataPlacement;
  }

  if (dataTheme !== undefined) {
    elementProps['data-theme'] = dataTheme;
  }

  if (dataTooltip !== undefined) {
    elementProps['data-tooltip'] = dataTooltip;
  }

  if (dir !== undefined) {
    elementProps['dir'] = dir;
  }

  if (dirname !== undefined) {
    elementProps['dirname'] = dirname;
  }

  if (disabled !== undefined) {
    elementProps['disabled'] = disabled;
  }

  if (draggable !== undefined) {
    elementProps['draggable'] = draggable;
  }

  if (form !== undefined) {
    elementProps['form'] = form;
  }

  if (formaction !== undefined) {
    elementProps['formaction'] = formaction;
  }

  if (formenctype !== undefined) {
    elementProps['formenctype'] = formenctype;
  }

  if (formmethod !== undefined) {
    elementProps['formmethod'] = formmethod;
  }

  if (formnovalidate !== undefined) {
    elementProps['formnovalidate'] = formnovalidate;
  }

  if (formtarget !== undefined) {
    elementProps['formtarget'] = formtarget;
  }

  if (height !== undefined) {
    elementProps['height'] = height;
  }

  if (hidden !== undefined) {
    elementProps['hidden'] = hidden;
  }

  if (id !== undefined) {
    elementProps['id'] = id;
  }

  if (inputmode !== undefined) {
    elementProps['inputmode'] = inputmode;
  }

  if (lang !== undefined) {
    elementProps['lang'] = lang;
  }

  if (list !== undefined) {
    elementProps['list'] = list;
  }

  if (max !== undefined) {
    elementProps['max'] = max;
  }

  if (maxlength !== undefined) {
    elementProps['maxlength'] = maxlength;
  }

  if (min !== undefined) {
    elementProps['min'] = min;
  }

  if (minlength !== undefined) {
    elementProps['minlength'] = minlength;
  }

  if (multiple !== undefined) {
    elementProps['multiple'] = multiple;
  }

  if (name !== undefined) {
    elementProps['name'] = name;
  }

  if (pattern !== undefined) {
    elementProps['pattern'] = pattern;
  }

  if (placeholder !== undefined) {
    elementProps['placeholder'] = placeholder;
  }

  if (popovertarget !== undefined) {
    elementProps['popovertarget'] = popovertarget;
  }

  if (popovertargetaction !== undefined) {
    elementProps['popovertargetaction'] = popovertargetaction;
  }

  if (readonly !== undefined) {
    elementProps['readonly'] = readonly;
  }

  if (required !== undefined) {
    elementProps['required'] = required;
  }

  if (role !== undefined) {
    elementProps['role'] = role;
  }

  if (size !== undefined) {
    elementProps['size'] = size;
  }

  if (spellcheck !== undefined) {
    elementProps['spellcheck'] = spellcheck;
  }

  if (src !== undefined) {
    elementProps['src'] = src;
  }

  if (step !== undefined) {
    elementProps['step'] = step;
  }

  if (style !== undefined) {
    elementProps['style'] = style;
  }

  if (tabindex !== undefined) {
    elementProps['tabindex'] = tabindex;
  }

  if (title !== undefined) {
    elementProps['title'] = title;
  }

  if (translate !== undefined) {
    elementProps['translate'] = translate;
  }

  if (type !== undefined) {
    elementProps['type'] = type;
  }

  if (value !== undefined) {
    elementProps['value'] = value;
  }

  if (width !== undefined) {
    elementProps['width'] = width;
  }

  return React.createElement(
    'input',
    elementProps
  );
};

Input.displayName = 'Input';
