/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 7, 2025 17:23:43
 * @component Select
 * @description The select element represents a control for selecting amongst a set of options.
 */

import React from 'react';

export interface SelectProps {
  /** The content to display in the element */
  children?: React.ReactNode;
  /** CSS class names */
  className?: string;
  accesskey?: string;
  /** Identifies the element(s) whose contents or presence are controlled by this element. Value is a list of IDs separated by a space */
  ariaControls?: string;
  /** Indicates that the element is perceivable but disabled, so it is not editable or otherwise operable. */
  ariaDisabled?: 'false' | 'true';
  /** Indicates that the value entered does not conform to the expected format. */
  ariaInvalid?: 'false' | 'true' | 'grammar' | 'spelling';
  /** Defines a string value that labels the current element for assistive technologies. */
  ariaLabel?: 'breadcrumb';
  autocapitalize?: 'none' | 'sentences' | 'words' | 'characters';
  autocomplete?: 'off' | 'on';
  /** Specifies controls whether autocorrection of editable text is enabled for spelling and/or punctuation errors. Default is on. */
  autocorrect?: 'off' | 'on';
  autofocus?: boolean;
  contenteditable?: 'true' | 'false' | 'inherit';
  /** Custom data attributes (data-*) */
  data?: Record<string, string>;
  dataPlacement?: 'top' | 'left' | 'right' | 'bottom';
  dataTheme?: 'light' | 'dark';
  dataTooltip?: string;
  dir?: 'ltr' | 'rtl' | 'auto';
  /** When present, it specifies that an input element should be disabled. */
  disabled?: boolean;
  draggable?: boolean;
  /** Associates the button with a form element by ID. Allows buttons to be associated with forms anywhere in the document, not just inside a form element. Can override ancestor form association. Element-specific to button, input, object, select, textarea, and fieldset. */
  form?: string;
  hidden?: boolean;
  id?: string;
  inputmode?: 'none' | 'text' | 'decimal' | 'numeric' | 'email' | 'tel' | 'url' | 'search';
  lang?: string;
  /** When present, it specifies that the user is allowed to enter more than one value in an input element. */
  multiple?: boolean;
  /** Specifies the name associated with the element. The meaning may vary depending on the context. */
  name?: string;
  /** When present, it specifies that an input field must be filled out before submitting the form. */
  required?: boolean;
  /** Specifies the height of a hr element in pixels. */
  size?: number;
  slot?: string;
  spellcheck?: 'true' | 'false';
  style?: React.CSSProperties;
  tabindex?: number;
  title?: string;
  translate?: 'yes' | 'no';
}

/**
 * Select - The select element represents a control for selecting amongst a set of options.
 */
export const Select: React.FC<SelectProps> = (props: SelectProps) => {
  const {
    children,
    className,
    accesskey,
    ariaControls,
    ariaDisabled,
    ariaInvalid,
    ariaLabel,
    autocapitalize,
    autocomplete,
    autocorrect,
    autofocus,
    contenteditable,
    data,
    dataPlacement,
    dataTheme,
    dataTooltip,
    dir,
    disabled,
    draggable,
    form,
    hidden,
    id,
    inputmode,
    lang,
    multiple,
    name,
    required,
    size,
    slot,
    spellcheck,
    style,
    tabindex,
    title,
    translate
  } = props;

  const elementProps: React.HTMLAttributes<HTMLElement> & Record<string, any> = {};

  if (className) {
    elementProps.className = className;
  }

  if (data) {
    Object.entries(data).forEach(([key, value]) => {
      elementProps[`data-${key}`] = value;
    });
  }

  if (accesskey !== undefined) {
    elementProps['accesskey'] = accesskey;
  }

  if (ariaControls !== undefined) {
    elementProps['aria-controls'] = ariaControls;
  }

  if (ariaDisabled !== undefined) {
    elementProps['aria-disabled'] = ariaDisabled;
  }

  if (ariaInvalid !== undefined) {
    elementProps['aria-invalid'] = ariaInvalid;
  }

  if (ariaLabel !== undefined) {
    elementProps['aria-label'] = ariaLabel;
  }

  if (autocapitalize !== undefined) {
    elementProps['autocapitalize'] = autocapitalize;
  }

  if (autocomplete !== undefined) {
    elementProps['autocomplete'] = autocomplete;
  }

  if (autocorrect !== undefined) {
    elementProps['autocorrect'] = autocorrect;
  }

  if (autofocus !== undefined) {
    elementProps['autofocus'] = autofocus;
  }

  if (contenteditable !== undefined) {
    elementProps['contenteditable'] = contenteditable;
  }

  if (dataPlacement !== undefined) {
    elementProps['data-placement'] = dataPlacement;
  }

  if (dataTheme !== undefined) {
    elementProps['data-theme'] = dataTheme;
  }

  if (dataTooltip !== undefined) {
    elementProps['data-tooltip'] = dataTooltip;
  }

  if (dir !== undefined) {
    elementProps['dir'] = dir;
  }

  if (disabled !== undefined) {
    elementProps['disabled'] = disabled;
  }

  if (draggable !== undefined) {
    elementProps['draggable'] = draggable;
  }

  if (form !== undefined) {
    elementProps['form'] = form;
  }

  if (hidden !== undefined) {
    elementProps['hidden'] = hidden;
  }

  if (id !== undefined) {
    elementProps['id'] = id;
  }

  if (inputmode !== undefined) {
    elementProps['inputmode'] = inputmode;
  }

  if (lang !== undefined) {
    elementProps['lang'] = lang;
  }

  if (multiple !== undefined) {
    elementProps['multiple'] = multiple;
  }

  if (name !== undefined) {
    elementProps['name'] = name;
  }

  if (required !== undefined) {
    elementProps['required'] = required;
  }

  if (size !== undefined) {
    elementProps['size'] = size;
  }

  if (slot !== undefined) {
    elementProps['slot'] = slot;
  }

  if (spellcheck !== undefined) {
    elementProps['spellcheck'] = spellcheck;
  }

  if (style !== undefined) {
    elementProps['style'] = style;
  }

  if (tabindex !== undefined) {
    elementProps['tabindex'] = tabindex;
  }

  if (title !== undefined) {
    elementProps['title'] = title;
  }

  if (translate !== undefined) {
    elementProps['translate'] = translate;
  }

  return React.createElement(
    'select',
    elementProps,
    children
  );
};

Select.displayName = 'Select';
