/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 7, 2025 17:23:47
 * @component Head
 * @description The head element contains meta-information about the HTML document, including its title and links to its scripts and stylesheets.
 */

import React from 'react';

export interface HeadProps {
  /** The content to display in the element */
  children?: React.ReactNode;
  /** CSS class names */
  className?: string;
  /** Custom data attributes (data-*) */
  data?: Record<string, string>;
}

/**
 * Head - The head element contains meta-information about the HTML document, including its title and links to its scripts and stylesheets.
 */
export const Head: React.FC<HeadProps> = (props: HeadProps) => {
  const {
    children,
    className,
    data
  } = props;

  const elementProps: React.HTMLAttributes<HTMLElement> & Record<string, any> = {};

  if (className) {
    elementProps.className = className;
  }

  if (data) {
    Object.entries(data).forEach(([key, value]) => {
      elementProps[`data-${key}`] = value;
    });
  }

  return React.createElement(
    'head',
    elementProps,
    children
  );
};

Head.displayName = 'Head';
