/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 7, 2025 17:23:47
 * @component Link
 * @description The link element defines a link between a document and an external resource. It is used to link to external stylesheets.
 */

import React from 'react';

export interface LinkProps {
  /** CSS class names */
  className?: string;
  crossorigin?: 'anonymous' | 'use-credentials';
  /** Custom data attributes (data-*) */
  data?: Record<string, string>;
  dir?: 'ltr' | 'rtl' | 'auto';
  hidden?: boolean;
  /** Specifies the URL of the linked resource. Special protocols such as mailto: or tel: can be used. */
  href: string;
  /** Specifies the language of the linked resource. */
  hreflang?: string;
  id?: string;
  /** Specifies the integrity value of a resource. */
  integrity?: string;
  lang?: string;
  /** Specifies the media type for which the linked resource or style sheet is intended. */
  media?: string;
  /** Specifies the referrer policy for fetches initiated by the element. */
  referrerpolicy?: 'no-referrer' | 'no-referrer-when-downgrade' | 'origin' | 'origin-when-cross-origin' | 'same-origin' | 'strict-origin' | 'strict-origin-when-cross-origin' | 'unsafe-url';
  /** Specifies the relationship between the current document and the linked document. */
  rel?: 'alternate' | 'author' | 'bookmark' | 'canonical' | 'help' | 'icon' | 'license' | 'manifest' | 'next' | 'nofollow' | 'noreferrer' | 'prefetch' | 'prev' | 'search' | 'stylesheet' | 'tag';
  /** Specifies the sizes of the images or icons for different display/window sizes. */
  sizes?: string;
  style?: React.CSSProperties;
  title?: string;
  /** Specifies the media type of the linked resource. */
  type?: string;
}

/**
 * Link - The link element defines a link between a document and an external resource. It is used to link to external stylesheets.
 */
export const Link: React.FC<LinkProps> = (props: LinkProps) => {
  const {
    className,
    crossorigin,
    data,
    dir,
    hidden,
    href,
    hreflang,
    id,
    integrity,
    lang,
    media,
    referrerpolicy,
    rel,
    sizes,
    style,
    title,
    type
  } = props;

  const elementProps: React.HTMLAttributes<HTMLElement> & Record<string, any> = {};

  if (className) {
    elementProps.className = className;
  }

  if (data) {
    Object.entries(data).forEach(([key, value]) => {
      elementProps[`data-${key}`] = value;
    });
  }

  if (crossorigin !== undefined) {
    elementProps['crossorigin'] = crossorigin;
  }

  if (dir !== undefined) {
    elementProps['dir'] = dir;
  }

  if (hidden !== undefined) {
    elementProps['hidden'] = hidden;
  }

  if (href !== undefined) {
    elementProps['href'] = href;
  }

  if (hreflang !== undefined) {
    elementProps['hreflang'] = hreflang;
  }

  if (id !== undefined) {
    elementProps['id'] = id;
  }

  if (integrity !== undefined) {
    elementProps['integrity'] = integrity;
  }

  if (lang !== undefined) {
    elementProps['lang'] = lang;
  }

  if (media !== undefined) {
    elementProps['media'] = media;
  }

  if (referrerpolicy !== undefined) {
    elementProps['referrerpolicy'] = referrerpolicy;
  }

  if (rel !== undefined) {
    elementProps['rel'] = rel;
  }

  if (sizes !== undefined) {
    elementProps['sizes'] = sizes;
  }

  if (style !== undefined) {
    elementProps['style'] = style;
  }

  if (title !== undefined) {
    elementProps['title'] = title;
  }

  if (type !== undefined) {
    elementProps['type'] = type;
  }

  return React.createElement(
    'link',
    elementProps
  );
};

Link.displayName = 'Link';
