/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 7, 2025 17:23:47
 * @component Meta
 * @description The meta element provides metadata about the HTML document. Metadata will not be displayed on the page, but is machine-readable. Mainly used in the head but allowed inside the body if itemprop attribute is set.
 */

import React from 'react';

export interface MetaProps {
  /** CSS class names */
  className?: string;
  /** Specifies the character encoding for the resource. */
  charset?: string;
  /** Specifies the value associated with the http-equiv or name attribute. */
  content?: string;
  /** Custom data attributes (data-*) */
  data?: Record<string, string>;
  hidden?: boolean;
  /** Provides an HTTP header for the information/value of the content attribute. */
  httpEquiv?: 'content-language' | 'content-type' | 'default-style' | 'refresh';
  id?: string;
  lang?: string;
  /** Specifies the name associated with the element. The meaning may vary depending on the context. */
  name?: string;
  /** Specifies the content type of the value attribute when the http-equiv attribute is used. */
  scheme?: string;
  title?: string;
}

/**
 * Meta - The meta element provides metadata about the HTML document. Metadata will not be displayed on the page, but is machine-readable. Mainly used in the head but allowed inside the body if itemprop attribute is set.
 */
export const Meta: React.FC<MetaProps> = (props: MetaProps) => {
  const {
    className,
    charset,
    content,
    data,
    hidden,
    httpEquiv,
    id,
    lang,
    name,
    scheme,
    title
  } = props;

  const elementProps: React.HTMLAttributes<HTMLElement> & Record<string, any> = {};

  if (className) {
    elementProps.className = className;
  }

  if (data) {
    Object.entries(data).forEach(([key, value]) => {
      elementProps[`data-${key}`] = value;
    });
  }

  if (charset !== undefined) {
    elementProps['charset'] = charset;
  }

  if (content !== undefined) {
    elementProps['content'] = content;
  }

  if (hidden !== undefined) {
    elementProps['hidden'] = hidden;
  }

  if (httpEquiv !== undefined) {
    elementProps['http-equiv'] = httpEquiv;
  }

  if (id !== undefined) {
    elementProps['id'] = id;
  }

  if (lang !== undefined) {
    elementProps['lang'] = lang;
  }

  if (name !== undefined) {
    elementProps['name'] = name;
  }

  if (scheme !== undefined) {
    elementProps['scheme'] = scheme;
  }

  if (title !== undefined) {
    elementProps['title'] = title;
  }

  return React.createElement(
    'meta',
    elementProps
  );
};

Meta.displayName = 'Meta';
