/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 7, 2025 17:23:47
 * @component Track
 * @description The track element is used as a child of the media elements—audio and video. It lets you specify timed text tracks (or time-based data), for example to automatically handle subtitles. The tracks are formatted in WebVTT format (.vtt files) — Web Video Text Tracks.
 */

import React from 'react';

export interface TrackProps {
  /** CSS class names */
  className?: string;
  /** Custom data attributes (data-*) */
  data?: Record<string, string>;
  hidden?: boolean;
  /** Specifies that the track should be enabled by default when the page loads. */
  htmlDefault?: boolean;
  id?: string;
  kind?: 'captions' | 'chapters' | 'descriptions' | 'metadata' | 'subtitles';
  /** Specifies a label for the associated form control, option group, or option. */
  label?: string;
  lang?: string;
  /** Specifies the URL of the external resource to be embedded or referenced. */
  src: string;
  /** Specifies the language of the track text data. */
  srclang?: string;
  style?: React.CSSProperties;
}

/**
 * Track - The track element is used as a child of the media elements—audio and video. It lets you specify timed text tracks (or time-based data), for example to automatically handle subtitles. The tracks are formatted in WebVTT format (.vtt files) — Web Video Text Tracks.
 */
export const Track: React.FC<TrackProps> = (props: TrackProps) => {
  const {
    className,
    data,
    hidden,
    htmlDefault,
    id,
    kind,
    label,
    lang,
    src,
    srclang,
    style
  } = props;

  const elementProps: React.HTMLAttributes<HTMLElement> & Record<string, any> = {};

  if (className) {
    elementProps.className = className;
  }

  if (data) {
    Object.entries(data).forEach(([key, value]) => {
      elementProps[`data-${key}`] = value;
    });
  }

  if (hidden !== undefined) {
    elementProps['hidden'] = hidden;
  }

  if (htmlDefault !== undefined) {
    elementProps['default'] = htmlDefault;
  }

  if (id !== undefined) {
    elementProps['id'] = id;
  }

  if (kind !== undefined) {
    elementProps['kind'] = kind;
  }

  if (label !== undefined) {
    elementProps['label'] = label;
  }

  if (lang !== undefined) {
    elementProps['lang'] = lang;
  }

  if (src !== undefined) {
    elementProps['src'] = src;
  }

  if (srclang !== undefined) {
    elementProps['srclang'] = srclang;
  }

  if (style !== undefined) {
    elementProps['style'] = style;
  }

  return React.createElement(
    'track',
    elementProps
  );
};

Track.displayName = 'Track';
