/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 13, 2025 17:52:38
 * @component Body
 * @description The body element represents the content of an HTML document. All the contents such as text, images, headings, links, tables, etc. are placed between the body tags.
 */

import React from 'react';

export interface BodyProps {
  /** The content to display in the element */
  children?: React.ReactNode;
  /** CSS class names */
  className?: string;
  accesskey?: string;
  /** Custom data attributes (data-*) */
  data?: Record<string, string>;
  dir?: 'ltr' | 'rtl' | 'auto';
  draggable?: boolean;
  hidden?: boolean;
  id?: string;
  lang?: string;
  /** Fires after the associated document has started printing or the print preview has been closed. */
  onafterprint?: string;
  /** Fires before the associated document is printed or previewed for printing. */
  onbeforeprint?: string;
  /** Fires before the user navigates away from the page. */
  onbeforeunload?: string;
  /** Fires when the fragment identifier part of the URL changes. */
  onhashchange?: string;
  /** Fires when the user changes the preferred language of the user interface. */
  onlanguagechange?: string;
  /** Fires when a message is received from a different browsing context (e.g., an iframe). */
  onmessage?: string;
  /** Fires when an error occurs while receiving a message from a different browsing context. */
  onmessageerror?: string;
  /** Fires when the browser goes offline. */
  onoffline?: string;
  /** Fires when the browser goes online. */
  ononline?: string;
  /** Fires when the user navigates away from a page. */
  onpagehide?: string;
  /** Fires when the user navigates to a page. */
  onpageshow?: string;
  /** Fires when the user navigates through the history by clicking the browser's Back or Forward buttons. */
  onpopstate?: string;
  /** Fires when a Promise is rejected and the rejection is handled by a Promise handler (e.g., catch). */
  onrejectionhandled?: string;
  /** Fires when a storage area (e.g., localStorage or sessionStorage) changes. */
  onstorage?: string;
  /** Fires when a Promise is rejected but there is no rejection handler (e.g., catch). */
  onunhandledrejection?: string;
  /** Fires when the user is navigating away from the page (similar to onbeforeunload). */
  onunload?: string;
  style?: React.CSSProperties;
  tabindex?: number;
  title?: string;
  translate?: 'yes' | 'no';
}

/**
 * Body - The body element represents the content of an HTML document. All the contents such as text, images, headings, links, tables, etc. are placed between the body tags.
 */
export const Body: React.FC<BodyProps> = (props: BodyProps) => {
  const {
    children,
    className,
    accesskey,
    data,
    dir,
    draggable,
    hidden,
    id,
    lang,
    onafterprint,
    onbeforeprint,
    onbeforeunload,
    onhashchange,
    onlanguagechange,
    onmessage,
    onmessageerror,
    onoffline,
    ononline,
    onpagehide,
    onpageshow,
    onpopstate,
    onrejectionhandled,
    onstorage,
    onunhandledrejection,
    onunload,
    style,
    tabindex,
    title,
    translate
  } = props;

  const elementProps: React.HTMLAttributes<HTMLElement> & Record<string, any> = {};

  // Handle data attributes specially
  if (data) {
    Object.entries(data).forEach(([key, value]) => {
      elementProps[`data-${key}`] = value;
    });
  }

  // Convert camelCase to kebab-case for attribute names
  const toKebabCase = (str: string): string => {
    return str.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
  };

  // Props to exclude from automatic mapping
  const excludedProps = new Set(['children', 'data']);

  // Iterate over all props and map them to element attributes
  Object.entries(props).forEach(([key, value]) => {
    if (excludedProps.has(key) || value === undefined) {
      return;
    }

    // Convert camelCase aria/contenteditable/autocapitalize to kebab-case
    const attrName = key.startsWith('aria') || key === 'contenteditable' || key === 'autocapitalize' 
      ? toKebabCase(key)
      : key;

    // Handle boolean props that need explicit conversion
    if (typeof value === 'boolean' && (key === 'draggable' || key === 'hidden')) {
      elementProps[attrName] = value ? true : false;
    } else {
      elementProps[attrName] = value;
    }
  });

  return React.createElement(
    'body',
    elementProps,
    children
  );
};

Body.displayName = 'Body';
