/**
 *
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 8, 2025 12:10
 * @component Table Row
 * @description The tr element represents a row of cells in a table.
 */

export default {
  title: "HTML5/Block Elements/Table Row",
  tags: ["autodocs"],
  parameters: {
    actions: {
      handles: ['change'],
    },
    layout: "centered",
    componentSubtitle: "Block Element",
    docs: {
      inlineStories: true,
      source: true,
      description: {
        component: "The tr element represents a row of cells in a table.",
      },
    },
  },
  argTypes: {
    text: {
      type: {
        name: "string",
        required: true
      },
      description: "The text or HTML to display in the element",
      defaultValue: "Sample text",
      control: {
        type: "text"
      },
    },
    accesskey: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    align: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the horizontal alignment of each row cell. The possible enumerated values are left, center, right, justify, and char. When supported, the char value aligns the textual content on the character defined in the char attribute and on offset defined by the charoff attribute. Use the text-align CSS property instead, as this attribute is deprecated.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "left", "center", "right", "justify", "char"],
    },
    ariaAtomic: {
      type: {
        name: "string",
        required: false
      },
      description: "Indicates whether assistive technologies should present the entire region as a whole when changes occur.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "false", "true"],
    },
    ariaBusy: {
      type: {
        name: "string",
        required: false
      },
      description: "The aria-busy attribute is used to indicate whether an element is currently busy or not.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "true", "false"],
    },
    ariaColcount: {
      type: {
        name: "number",
        required: false
      },
      description: "Defines the total number of columns in a table or grid.",
      defaultValue: 0,
      control: {
        type: "number"
      },
    },
    ariaControls: {
      type: {
        name: "string",
        required: false
      },
      description: "Identifies the element(s) whose contents or presence are controlled by this element. Value is a list of IDs separated by a space",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaDescribedby: {
      type: {
        name: "string",
        required: false
      },
      description: "Identifies the element(s) that describes the object. Value is a list of IDs separated by a space",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaDetails: {
      type: {
        name: "string",
        required: false
      },
      description: "References an element that provides additional details about the current element.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaHidden: {
      type: {
        name: "string",
        required: false
      },
      description: "Indicates whether the element is exposed to an accessibility API. Use with caution on interactive elements. Set to true only on decorative elements such as icons, or when nav isnt visible",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "false", "true"],
    },
    ariaKeyshortcuts: {
      type: {
        name: "string",
        required: false
      },
      description: "Defines keyboard shortcuts available for the element.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaLabelledby: {
      type: {
        name: "string",
        required: false
      },
      description: "Identifies the element(s) that labels the current element. Value is a list of IDs separated by a space",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaLevel: {
      type: {
        name: "number",
        required: false
      },
      description: "Defines the hierarchical level of an element (e.g., headings, tree items).",
      defaultValue: 0,
      control: {
        type: "number"
      },
    },
    ariaLive: {
      type: {
        name: "string",
        required: false
      },
      description: "Defines how updates to the element should be announced to screen readers.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "off", "polite", "assertive"],
    },
    ariaPosinset: {
      type: {
        name: "number",
        required: false
      },
      description: "Defines an element\'s position within a set (1-based index).",
      defaultValue: 0,
      control: {
        type: "number"
      },
    },
    ariaRelevant: {
      type: {
        name: "string",
        required: false
      },
      description: "Indicates what content changes should be announced in a live region.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "additions", "removals", "text", "all", "additions text"],
    },
    ariaRoledescription: {
      type: {
        name: "string",
        required: false
      },
      description: "Provides a human-readable custom role description for assistive technologies.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaRowcount: {
      type: {
        name: "number",
        required: false
      },
      description: "Defines the total number of rows in a table or grid.",
      defaultValue: 0,
      control: {
        type: "number"
      },
    },
    ariaSelected: {
      type: {
        name: "string",
        required: false
      },
      description: "Indicates whether an item is selected (e.g., in a list, table, or tree).",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "false", "true", "undefined"],
    },
    ariaSetsize: {
      type: {
        name: "number",
        required: false
      },
      description: "Specifies the total number of items in a set.",
      defaultValue: 0,
      control: {
        type: "number"
      },
    },
    ariaSort: {
      type: {
        name: "string",
        required: false
      },
      description: "Defines the sorting order of a column.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "none", "ascending", "descending", "other"],
    },
    autocapitalize: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "none", "sentences", "words", "characters"],
    },
    autofocus: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    bgcolor: {
      type: {
        name: "string",
        required: false
      },
      description: "Defines the background color of each row cell. The value is an HTML color; either a 6-digit hexadecimal RGB code, prefixed by a #, or a color keyword. Other CSS <color> values are not supported. Use the background-color CSS property instead, as this attribute is deprecated.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    char: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the alignment of the content to a character of each row cell. Typical values for this include a period (.) when attempting to align numbers or monetary values. If align is not set to char, this attribute is ignored.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    charoff: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the number of characters to offset the row cell content from the alignment character specified by the char attribute.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    classProp: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    contenteditable: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "true", "false", "inherit"],
    },
    data: {
      type: {
        name: "object",
        required: false
      },
      description: "Custom data attributes (data-*). Provide an object with key-value pairs.",
      defaultValue: {},
      control: {
        type: "object"
      },
    },
    dir: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "ltr", "rtl", "auto"],
    },
    draggable: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    hidden: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    id: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    inputmode: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "none", "text", "decimal", "numeric", "email", "tel", "url", "search"],
    },
    lang: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    popover: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "auto", "hint", "manual"],
    },
    role: {
      type: {
        name: "string",
        required: false
      },
      description: "Defines the semantic purpose of an element for assistive technologies.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "alert", "application", "article", "banner", "button", "checkbox", "complementary", "contentinfo", "dialog", "form", "grid", "group", "heading", "img", "link", "list", "listbox", "listitem", "main", "menu", "menubar", "menuitem", "navigation", "none", "presentation", "radio", "region", "search", "status", "tab", "tablist", "tabpanel", "textbox", "toolbar", "tooltip"],
    },
    spellcheck: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "true", "false"],
    },
    style: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    tabindex: {
      type: {
        name: "number",
        required: false
      },
      defaultValue: 0,
      control: {
        type: "number"
      },
    },
    title: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    translate: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "yes", "no"],
    },
    valign: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the vertical alignment of each row cell. The possible enumerated values are baseline, bottom, middle, and top. Use the vertical-align CSS property instead, as this attribute is deprecated.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "baseline", "bottom", "middle", "top"],
    },
  },
  render: ({
    text,
    accesskey,
    align,
    ariaAtomic,
    ariaBusy,
    ariaColcount,
    ariaControls,
    ariaDescribedby,
    ariaDetails,
    ariaHidden,
    ariaKeyshortcuts,
    ariaLabelledby,
    ariaLevel,
    ariaLive,
    ariaPosinset,
    ariaRelevant,
    ariaRoledescription,
    ariaRowcount,
    ariaSelected,
    ariaSetsize,
    ariaSort,
    autocapitalize,
    autofocus,
    bgcolor,
    char,
    charoff,
    classProp,
    contenteditable,
    data,
    dir,
    draggable,
    hidden,
    id,
    inputmode,
    lang,
    popover,
    role,
    spellcheck,
    style,
    tabindex,
    title,
    translate,
    valign,
  }) => {
    let el = document.createElement("tr");
    el.innerHTML = text;
    if (accesskey) {
      el.setAttribute('accesskey', accesskey);
    }
    if (align) {
      el.setAttribute('align', align);
    }
    if (ariaAtomic) {
      el.setAttribute('aria-atomic', ariaAtomic);
    }
    if (ariaBusy) {
      el.setAttribute('aria-busy', ariaBusy);
    }
    if (ariaColcount) {
      el.setAttribute('aria-colcount', ariaColcount);
    }
    if (ariaControls) {
      el.setAttribute('aria-controls', ariaControls);
    }
    if (ariaDescribedby) {
      el.setAttribute('aria-describedby', ariaDescribedby);
    }
    if (ariaDetails) {
      el.setAttribute('aria-details', ariaDetails);
    }
    if (ariaHidden) {
      el.setAttribute('aria-hidden', ariaHidden);
    }
    if (ariaKeyshortcuts) {
      el.setAttribute('aria-keyshortcuts', ariaKeyshortcuts);
    }
    if (ariaLabelledby) {
      el.setAttribute('aria-labelledby', ariaLabelledby);
    }
    if (ariaLevel) {
      el.setAttribute('aria-level', ariaLevel);
    }
    if (ariaLive) {
      el.setAttribute('aria-live', ariaLive);
    }
    if (ariaPosinset) {
      el.setAttribute('aria-posinset', ariaPosinset);
    }
    if (ariaRelevant) {
      el.setAttribute('aria-relevant', ariaRelevant);
    }
    if (ariaRoledescription) {
      el.setAttribute('aria-roledescription', ariaRoledescription);
    }
    if (ariaRowcount) {
      el.setAttribute('aria-rowcount', ariaRowcount);
    }
    if (ariaSelected) {
      el.setAttribute('aria-selected', ariaSelected);
    }
    if (ariaSetsize) {
      el.setAttribute('aria-setsize', ariaSetsize);
    }
    if (ariaSort) {
      el.setAttribute('aria-sort', ariaSort);
    }
    if (autocapitalize) {
      el.setAttribute('autocapitalize', autocapitalize);
    }
    if (autofocus) {
      el.setAttribute('autofocus', autofocus);
    }
    if (bgcolor) {
      el.setAttribute('bgcolor', bgcolor);
    }
    if (char) {
      el.setAttribute('char', char);
    }
    if (charoff) {
      el.setAttribute('charoff', charoff);
    }
    if (classProp) {
      el.setAttribute('class', classProp);
    }
    if (contenteditable) {
      el.setAttribute('contenteditable', contenteditable);
    }
    if (data && typeof data === 'object') {
      Object.keys(data).forEach(key => {
        el.setAttribute(`data-${key}`, data[key]);
      });
    }
    if (dir) {
      el.setAttribute('dir', dir);
    }
    if (draggable) {
      el.setAttribute('draggable', draggable);
    }
    if (hidden) {
      el.setAttribute('hidden', hidden);
    }
    if (id) {
      el.setAttribute('id', id);
    }
    if (inputmode) {
      el.setAttribute('inputmode', inputmode);
    }
    if (lang) {
      el.setAttribute('lang', lang);
    }
    if (popover) {
      el.setAttribute('popover', popover);
    }
    if (role) {
      el.setAttribute('role', role);
    }
    if (spellcheck) {
      el.setAttribute('spellcheck', spellcheck);
    }
    if (style) {
      el.setAttribute('style', style);
    }
    if (tabindex) {
      el.setAttribute('tabindex', tabindex);
    }
    if (title) {
      el.setAttribute('title', title);
    }
    if (translate) {
      el.setAttribute('translate', translate);
    }
    if (valign) {
      el.setAttribute('valign', valign);
    }
    return el;
  },
  decorators: [],
};

export const Default = {
  parameters: {
    docs: {
      description: {
        story: 'Default story with all arguments set to default values'
      },
    },
  },
  args: {
    text: "Sample text",
    accesskey: "Sample value",
    align: "",
    ariaAtomic: "",
    ariaBusy: "",
    ariaColcount: 0,
    ariaControls: "Sample value",
    ariaDescribedby: "Sample value",
    ariaDetails: "Sample value",
    ariaHidden: "",
    ariaKeyshortcuts: "Sample value",
    ariaLabelledby: "Sample value",
    ariaLevel: 0,
    ariaLive: "",
    ariaPosinset: 0,
    ariaRelevant: "",
    ariaRoledescription: "Sample value",
    ariaRowcount: 0,
    ariaSelected: "",
    ariaSetsize: 0,
    ariaSort: "",
    autocapitalize: "",
    autofocus: false,
    bgcolor: "Sample value",
    char: "Sample value",
    charoff: "Sample value",
    classProp: "Sample value",
    contenteditable: "",
    data: {},
    dir: "",
    draggable: false,
    hidden: false,
    id: "Sample value",
    inputmode: "",
    lang: "Sample value",
    popover: "",
    role: "",
    spellcheck: "",
    style: "Sample value",
    tabindex: 0,
    title: "Sample value",
    translate: "",
    valign: "",
  },
};
