/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 13, 2025 17:52:41
 * @component Source
 * @description The source element allows authors to specify multiple media resources for media elements. It is an empty element. It is commonly used within the picture element.
 */

import React from 'react';

export interface SourceProps {
  /** CSS class names */
  className?: string;
  /** Custom data attributes (data-*) */
  data?: Record<string, string>;
  hidden?: boolean;
  id?: string;
  /** Specifies the media type for which the linked resource or style sheet is intended. */
  media?: string;
  /** Specifies the sizes of the images or icons for different display/window sizes. */
  sizes?: string;
  /** Specifies the URL of the external resource to be embedded or referenced. */
  src: string;
  /** Specifies a list of possible image sources for the browser to use. */
  srcset?: string;
  /** Specifies the media type of the linked resource. */
  type?: string;
}

/**
 * Source - The source element allows authors to specify multiple media resources for media elements. It is an empty element. It is commonly used within the picture element.
 */
export const Source: React.FC<SourceProps> = (props: SourceProps) => {
  const {
    className,
    data,
    hidden,
    id,
    media,
    sizes,
    src,
    srcset,
    type
  } = props;

  const elementProps: React.HTMLAttributes<HTMLElement> & Record<string, any> = {};

  // Handle data attributes specially
  if (data) {
    Object.entries(data).forEach(([key, value]) => {
      elementProps[`data-${key}`] = value;
    });
  }

  // Convert camelCase to kebab-case for attribute names
  const toKebabCase = (str: string): string => {
    return str.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
  };

  // Props to exclude from automatic mapping
  const excludedProps = new Set(['children', 'data']);

  // Iterate over all props and map them to element attributes
  Object.entries(props).forEach(([key, value]) => {
    if (excludedProps.has(key) || value === undefined) {
      return;
    }

    // Convert camelCase aria/contenteditable/autocapitalize to kebab-case
    const attrName = key.startsWith('aria') || key === 'contenteditable' || key === 'autocapitalize' 
      ? toKebabCase(key)
      : key;

    // Handle boolean props that need explicit conversion
    if (typeof value === 'boolean' && (key === 'hidden')) {
      elementProps[attrName] = value ? true : false;
    } else {
      elementProps[attrName] = value;
    }
  });

  return React.createElement(
    'source',
    elementProps
  );
};

Source.displayName = 'Source';
