/**
 *
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 13, 2025 17:52
 * @component Video
 * @description The video element is used to embed video content in a document, such as a movie clip or other video streams.
 */

export default {
  title: "HTML5/Block Elements/Video",
  tags: ["autodocs"],
  parameters: {
    actions: {
      handles: ['change'],
    },
    layout: "centered",
    componentSubtitle: "Block Element",
    docs: {
      inlineStories: true,
      source: true,
      description: {
        component: "The video element is used to embed video content in a document, such as a movie clip or other video streams.",
      },
    },
  },
  argTypes: {
    text: {
      type: {
        name: "string",
        required: true
      },
      description: "The text or HTML to display in the element",
      defaultValue: "Sample text",
      control: {
        type: "text"
      },
    },
    accesskey: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaAtomic: {
      type: {
        name: "string",
        required: false
      },
      description: "Indicates whether assistive technologies should present the entire region as a whole when changes occur.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "false", "true"],
    },
    ariaBusy: {
      type: {
        name: "string",
        required: false
      },
      description: "The aria-busy attribute is used to indicate whether an element is currently busy or not.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "true", "false"],
    },
    ariaControls: {
      type: {
        name: "string",
        required: false
      },
      description: "Identifies the element(s) whose contents or presence are controlled by this element. Value is a list of IDs separated by a space",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaDescribedby: {
      type: {
        name: "string",
        required: false
      },
      description: "Identifies the element(s) that describes the object. Value is a list of IDs separated by a space",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaDetails: {
      type: {
        name: "string",
        required: false
      },
      description: "References an element that provides additional details about the current element.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaHidden: {
      type: {
        name: "string",
        required: false
      },
      description: "Indicates whether the element is exposed to an accessibility API. Use with caution on interactive elements. Set to true only on decorative elements such as icons, or when nav isnt visible",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "false", "true"],
    },
    ariaKeyshortcuts: {
      type: {
        name: "string",
        required: false
      },
      description: "Defines keyboard shortcuts available for the element.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaLabelledby: {
      type: {
        name: "string",
        required: false
      },
      description: "Identifies the element(s) that labels the current element. Value is a list of IDs separated by a space",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaLive: {
      type: {
        name: "string",
        required: false
      },
      description: "Defines how updates to the element should be announced to screen readers.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "off", "polite", "assertive"],
    },
    ariaRelevant: {
      type: {
        name: "string",
        required: false
      },
      description: "Indicates what content changes should be announced in a live region.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "additions", "removals", "text", "all", "additions text"],
    },
    ariaRoledescription: {
      type: {
        name: "string",
        required: false
      },
      description: "Provides a human-readable custom role description for assistive technologies.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    autocapitalize: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "none", "sentences", "words", "characters"],
    },
    autofocus: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    autoplay: {
      type: {
        name: "boolean",
        required: false
      },
      description: "When present, it specifies that the audio or video will automatically start playing as soon as it can do so without stopping.",
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    classProp: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    contenteditable: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "true", "false", "inherit"],
    },
    controls: {
      type: {
        name: "boolean",
        required: false
      },
      description: "When present, it specifies that audio or video controls should be displayed (such as play, pause, and volume).",
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    crossorigin: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "anonymous", "use-credentials"],
    },
    data: {
      type: {
        name: "object",
        required: false
      },
      description: "Custom data attributes (data-*). Provide an object with key-value pairs.",
      defaultValue: {},
      control: {
        type: "object"
      },
    },
    dir: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "ltr", "rtl", "auto"],
    },
    draggable: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    height: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the height of the element. The meaning may vary depending on the element type. Accepts integers, pixels (px), and percentages (%).",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    hidden: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    id: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    inputmode: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "none", "text", "decimal", "numeric", "email", "tel", "url", "search"],
    },
    lang: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    loop: {
      type: {
        name: "boolean",
        required: false
      },
      description: "When present, it specifies that the audio or video will start over again every time it is finished.",
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    muted: {
      type: {
        name: "boolean",
        required: false
      },
      description: "When present, it specifies that the audio output of the video should be muted.",
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    popover: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "auto", "hint", "manual"],
    },
    poster: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the URL of an image to be displayed as the video\'s poster (thumbnail) image.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    preload: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "auto", "metadata", "none"],
    },
    role: {
      type: {
        name: "string",
        required: false
      },
      description: "Defines the semantic purpose of an element for assistive technologies.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "alert", "application", "article", "banner", "button", "checkbox", "complementary", "contentinfo", "dialog", "form", "grid", "group", "heading", "img", "link", "list", "listbox", "listitem", "main", "menu", "menubar", "menuitem", "navigation", "none", "presentation", "radio", "region", "search", "status", "tab", "tablist", "tabpanel", "textbox", "toolbar", "tooltip"],
    },
    slot: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    spellcheck: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "true", "false"],
    },
    src: {
      type: {
        name: "string",
        required: true
      },
      description: "Specifies the URL of the external resource to be embedded or referenced.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    style: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    tabindex: {
      type: {
        name: "number",
        required: false
      },
      defaultValue: 0,
      control: {
        type: "number"
      },
    },
    title: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    translate: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "yes", "no"],
    },
    width: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the width of the element. The meaning may vary depending on the element type. Accepts integers, pixels (px), and percentages (%).",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
  },
  render: ({
    text,
    accesskey,
    ariaAtomic,
    ariaBusy,
    ariaControls,
    ariaDescribedby,
    ariaDetails,
    ariaHidden,
    ariaKeyshortcuts,
    ariaLabelledby,
    ariaLive,
    ariaRelevant,
    ariaRoledescription,
    autocapitalize,
    autofocus,
    autoplay,
    classProp,
    contenteditable,
    controls,
    crossorigin,
    data,
    dir,
    draggable,
    height,
    hidden,
    id,
    inputmode,
    lang,
    loop,
    muted,
    popover,
    poster,
    preload,
    role,
    slot,
    spellcheck,
    src,
    style,
    tabindex,
    title,
    translate,
    width,
  }) => {
    let el = document.createElement("video");
    el.innerHTML = text;
    if (accesskey) {
      el.setAttribute('accesskey', accesskey);
    }
    if (ariaAtomic) {
      el.setAttribute('aria-atomic', ariaAtomic);
    }
    if (ariaBusy) {
      el.setAttribute('aria-busy', ariaBusy);
    }
    if (ariaControls) {
      el.setAttribute('aria-controls', ariaControls);
    }
    if (ariaDescribedby) {
      el.setAttribute('aria-describedby', ariaDescribedby);
    }
    if (ariaDetails) {
      el.setAttribute('aria-details', ariaDetails);
    }
    if (ariaHidden) {
      el.setAttribute('aria-hidden', ariaHidden);
    }
    if (ariaKeyshortcuts) {
      el.setAttribute('aria-keyshortcuts', ariaKeyshortcuts);
    }
    if (ariaLabelledby) {
      el.setAttribute('aria-labelledby', ariaLabelledby);
    }
    if (ariaLive) {
      el.setAttribute('aria-live', ariaLive);
    }
    if (ariaRelevant) {
      el.setAttribute('aria-relevant', ariaRelevant);
    }
    if (ariaRoledescription) {
      el.setAttribute('aria-roledescription', ariaRoledescription);
    }
    if (autocapitalize) {
      el.setAttribute('autocapitalize', autocapitalize);
    }
    if (autofocus) {
      el.setAttribute('autofocus', autofocus);
    }
    if (autoplay) {
      el.setAttribute('autoplay', autoplay);
    }
    if (classProp) {
      el.setAttribute('class', classProp);
    }
    if (contenteditable) {
      el.setAttribute('contenteditable', contenteditable);
    }
    if (controls) {
      el.setAttribute('controls', controls);
    }
    if (crossorigin) {
      el.setAttribute('crossorigin', crossorigin);
    }
    if (data && typeof data === 'object') {
      Object.keys(data).forEach(key => {
        el.setAttribute(`data-${key}`, data[key]);
      });
    }
    if (dir) {
      el.setAttribute('dir', dir);
    }
    if (draggable) {
      el.setAttribute('draggable', draggable);
    }
    if (height) {
      el.setAttribute('height', height);
    }
    if (hidden) {
      el.setAttribute('hidden', hidden);
    }
    if (id) {
      el.setAttribute('id', id);
    }
    if (inputmode) {
      el.setAttribute('inputmode', inputmode);
    }
    if (lang) {
      el.setAttribute('lang', lang);
    }
    if (loop) {
      el.setAttribute('loop', loop);
    }
    if (muted) {
      el.setAttribute('muted', muted);
    }
    if (popover) {
      el.setAttribute('popover', popover);
    }
    if (poster) {
      el.setAttribute('poster', poster);
    }
    if (preload) {
      el.setAttribute('preload', preload);
    }
    if (role) {
      el.setAttribute('role', role);
    }
    if (slot) {
      el.setAttribute('slot', slot);
    }
    if (spellcheck) {
      el.setAttribute('spellcheck', spellcheck);
    }
    if (src) {
      el.setAttribute('src', src);
    }
    if (style) {
      el.setAttribute('style', style);
    }
    if (tabindex) {
      el.setAttribute('tabindex', tabindex);
    }
    if (title) {
      el.setAttribute('title', title);
    }
    if (translate) {
      el.setAttribute('translate', translate);
    }
    if (width) {
      el.setAttribute('width', width);
    }
    return el;
  },
  decorators: [],
};

export const Default = {
  parameters: {
    docs: {
      description: {
        story: 'Default story with all arguments set to default values'
      },
    },
  },
  args: {
    text: "Sample text",
    accesskey: "Sample value",
    ariaAtomic: "",
    ariaBusy: "",
    ariaControls: "Sample value",
    ariaDescribedby: "Sample value",
    ariaDetails: "Sample value",
    ariaHidden: "",
    ariaKeyshortcuts: "Sample value",
    ariaLabelledby: "Sample value",
    ariaLive: "",
    ariaRelevant: "",
    ariaRoledescription: "Sample value",
    autocapitalize: "",
    autofocus: false,
    autoplay: false,
    classProp: "Sample value",
    contenteditable: "",
    controls: false,
    crossorigin: "",
    data: {},
    dir: "",
    draggable: false,
    height: "Sample value",
    hidden: false,
    id: "Sample value",
    inputmode: "",
    lang: "Sample value",
    loop: false,
    muted: false,
    popover: "",
    poster: "Sample value",
    preload: "",
    role: "",
    slot: "Sample value",
    spellcheck: "",
    src: "Sample value",
    style: "Sample value",
    tabindex: 0,
    title: "Sample value",
    translate: "",
    width: "Sample value",
  },
};
