/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 13, 2025 17:52:40
 * @component Horizontal Rule
 * @description The hr element represents a thematic break between paragraph-level elements. It is typically a horizontal rule or line.
 */

import React from 'react';

export interface HrProps {
  /** CSS class names */
  className?: string;
  /** Specifies the horizontal alignment of the element. */
  align?: 'center' | 'justify' | 'left' | 'right';
  color?: string;
  /** Custom data attributes (data-*) */
  data?: Record<string, string>;
  dir?: 'ltr' | 'rtl' | 'auto';
  hidden?: boolean;
  id?: string;
  lang?: string;
  noshade?: boolean;
  /** Specifies the height of a hr element in pixels. */
  size?: number;
  style?: React.CSSProperties;
  title?: string;
  /** Specifies the width of the element. The meaning may vary depending on the element type. Accepts integers, pixels (px), and percentages (%). */
  width?: string;
}

/**
 * Horizontal Rule - The hr element represents a thematic break between paragraph-level elements. It is typically a horizontal rule or line.
 */
export const Hr: React.FC<HrProps> = (props: HrProps) => {
  const {
    className,
    align,
    color,
    data,
    dir,
    hidden,
    id,
    lang,
    noshade,
    size,
    style,
    title,
    width
  } = props;

  const elementProps: React.HTMLAttributes<HTMLElement> & Record<string, any> = {};

  // Handle data attributes specially
  if (data) {
    Object.entries(data).forEach(([key, value]) => {
      elementProps[`data-${key}`] = value;
    });
  }

  // Convert camelCase to kebab-case for attribute names
  const toKebabCase = (str: string): string => {
    return str.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
  };

  // Props to exclude from automatic mapping
  const excludedProps = new Set(['children', 'data']);

  // Iterate over all props and map them to element attributes
  Object.entries(props).forEach(([key, value]) => {
    if (excludedProps.has(key) || value === undefined) {
      return;
    }

    // Convert camelCase aria/contenteditable/autocapitalize to kebab-case
    const attrName = key.startsWith('aria') || key === 'contenteditable' || key === 'autocapitalize' 
      ? toKebabCase(key)
      : key;

    // Handle boolean props that need explicit conversion
    if (typeof value === 'boolean' && (key === 'hidden' || key === 'noshade')) {
      elementProps[attrName] = value ? true : false;
    } else {
      elementProps[attrName] = value;
    }
  });

  return React.createElement(
    'hr',
    elementProps
  );
};

Hr.displayName = 'Hr';
