/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 13, 2025 17:52:41
 * @component Style
 * @description The style element is used to embed CSS styles directly into an HTML document.
 */

import React from 'react';

export interface StyleProps {
  /** The content to display in the element */
  children?: React.ReactNode;
  /** CSS class names */
  className?: string;
  /** Custom data attributes (data-*) */
  data?: Record<string, string>;
  dir?: 'ltr' | 'rtl' | 'auto';
  id?: string;
  lang?: string;
  /** Specifies the media type for which the linked resource or style sheet is intended. */
  media?: string;
  /** Specifies a cryptographic nonce that can be used in Content Security Policy (CSP) checks. */
  nonce?: string;
  /** Specifies additional information about the element, typically displayed as a tooltip. */
  title?: string;
  /** Specifies the media type of the inline styles. */
  type?: 'text/css';
}

/**
 * Style - The style element is used to embed CSS styles directly into an HTML document.
 */
export const Style: React.FC<StyleProps> = (props: StyleProps) => {
  const {
    children,
    className,
    data,
    dir,
    id,
    lang,
    media,
    nonce,
    title,
    type
  } = props;

  const elementProps: React.HTMLAttributes<HTMLElement> & Record<string, any> = {};

  // Handle data attributes specially
  if (data) {
    Object.entries(data).forEach(([key, value]) => {
      elementProps[`data-${key}`] = value;
    });
  }

  // Convert camelCase to kebab-case for attribute names
  const toKebabCase = (str: string): string => {
    return str.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
  };

  // Props to exclude from automatic mapping
  const excludedProps = new Set(['children', 'data']);

  // Iterate over all props and map them to element attributes
  Object.entries(props).forEach(([key, value]) => {
    if (excludedProps.has(key) || value === undefined) {
      return;
    }

    // Convert camelCase aria/contenteditable/autocapitalize to kebab-case
    const attrName = key.startsWith('aria') || key === 'contenteditable' || key === 'autocapitalize' 
      ? toKebabCase(key)
      : key;

    elementProps[attrName] = value;
  });

  return React.createElement(
    'style',
    elementProps,
    children
  );
};

Style.displayName = 'Style';
