/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 13, 2025 17:52:41
 * @component Area
 * @description The area element represents either a hyperlink with some text and a corresponding area on an image map, or a dead area on an image map.
 */

import React from 'react';

export interface AreaProps {
  /** CSS class names */
  className?: string;
  accesskey?: string;
  /** Specifies alternative text to be displayed when the image cannot be rendered. */
  alt: string;
  autocapitalize?: 'none' | 'sentences' | 'words' | 'characters';
  autofocus?: boolean;
  contenteditable?: 'true' | 'false' | 'inherit';
  /** Specifies the coordinates of the shape in a rectangular area or a polygonal area on an image map. */
  coords?: string;
  /** Custom data attributes (data-*) */
  data?: Record<string, string>;
  dir?: 'ltr' | 'rtl' | 'auto';
  /** Indicates that the linked content should be downloaded rather than displayed. */
  download?: string;
  draggable?: boolean;
  hidden?: boolean;
  /** Specifies the URL of the linked resource. Special protocols such as mailto: or tel: can be used. */
  href: string;
  /** Specifies the language of the linked resource. */
  hreflang?: string;
  id?: string;
  inputmode?: 'none' | 'text' | 'decimal' | 'numeric' | 'email' | 'tel' | 'url' | 'search';
  lang?: string;
  /** Specifies the relationship between the current document and the linked document. */
  rel?: 'alternate' | 'author' | 'bookmark' | 'canonical' | 'help' | 'icon' | 'license' | 'next' | 'nofollow' | 'noreferrer' | 'prefetch' | 'prev' | 'search' | 'stylesheet' | 'tag';
  shape?: 'circle' | 'default' | 'poly' | 'rect';
  spellcheck?: 'true' | 'false';
  style?: React.CSSProperties;
  tabindex?: number;
  /** Specifies where to open the linked document. */
  target?: '_blank' | '_parent' | '_self' | '_top';
  title?: string;
  translate?: 'yes' | 'no';
  /** Specifies the media type of the linked resource. */
  type?: string;
}

/**
 * Area - The area element represents either a hyperlink with some text and a corresponding area on an image map, or a dead area on an image map.
 */
export const Area: React.FC<AreaProps> = (props: AreaProps) => {
  const {
    className,
    accesskey,
    alt,
    autocapitalize,
    autofocus,
    contenteditable,
    coords,
    data,
    dir,
    download,
    draggable,
    hidden,
    href,
    hreflang,
    id,
    inputmode,
    lang,
    rel,
    shape,
    spellcheck,
    style,
    tabindex,
    target,
    title,
    translate,
    type
  } = props;

  const elementProps: React.HTMLAttributes<HTMLElement> & Record<string, any> = {};

  // Handle data attributes specially
  if (data) {
    Object.entries(data).forEach(([key, value]) => {
      elementProps[`data-${key}`] = value;
    });
  }

  // Convert camelCase to kebab-case for attribute names
  const toKebabCase = (str: string): string => {
    return str.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
  };

  // Props to exclude from automatic mapping
  const excludedProps = new Set(['children', 'data']);

  // Iterate over all props and map them to element attributes
  Object.entries(props).forEach(([key, value]) => {
    if (excludedProps.has(key) || value === undefined) {
      return;
    }

    // Convert camelCase aria/contenteditable/autocapitalize to kebab-case
    const attrName = key.startsWith('aria') || key === 'contenteditable' || key === 'autocapitalize' 
      ? toKebabCase(key)
      : key;

    // Handle boolean props that need explicit conversion
    if (typeof value === 'boolean' && (key === 'autofocus' || key === 'draggable' || key === 'hidden')) {
      elementProps[attrName] = value ? true : false;
    } else {
      elementProps[attrName] = value;
    }
  });

  return React.createElement(
    'area',
    elementProps
  );
};

Area.displayName = 'Area';
