/**
 *
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 8, 2025 12:10
 * @component Meter
 * @description The meter element represents a scalar measurement within a known range, or a fractional value.
 */

export default {
  title: "HTML5/Inline Elements/Meter",
  tags: ["autodocs"],
  parameters: {
    actions: {
      handles: ['change'],
    },
    layout: "centered",
    componentSubtitle: "Inline Element",
    docs: {
      inlineStories: true,
      source: true,
      description: {
        component: "The meter element represents a scalar measurement within a known range, or a fractional value.",
      },
    },
  },
  argTypes: {
    text: {
      type: {
        name: "string",
        required: true
      },
      description: "The text or HTML to display in the element",
      defaultValue: "Sample text",
      control: {
        type: "text"
      },
    },
    accesskey: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaAtomic: {
      type: {
        name: "string",
        required: false
      },
      description: "Indicates whether assistive technologies should present the entire region as a whole when changes occur.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "false", "true"],
    },
    ariaDetails: {
      type: {
        name: "string",
        required: false
      },
      description: "References an element that provides additional details about the current element.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaKeyshortcuts: {
      type: {
        name: "string",
        required: false
      },
      description: "Defines keyboard shortcuts available for the element.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaLive: {
      type: {
        name: "string",
        required: false
      },
      description: "Defines how updates to the element should be announced to screen readers.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "off", "polite", "assertive"],
    },
    ariaRelevant: {
      type: {
        name: "string",
        required: false
      },
      description: "Indicates what content changes should be announced in a live region.",
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "additions", "removals", "text", "all", "additions text"],
    },
    ariaRoledescription: {
      type: {
        name: "string",
        required: false
      },
      description: "Provides a human-readable custom role description for assistive technologies.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    ariaValuemax: {
      type: {
        name: "number",
        required: false
      },
      description: "Defines the maximum value for a range input.",
      defaultValue: 0,
      control: {
        type: "number"
      },
    },
    ariaValuemin: {
      type: {
        name: "number",
        required: false
      },
      description: "Defines the minimum value for a range input.",
      defaultValue: 0,
      control: {
        type: "number"
      },
    },
    ariaValuenow: {
      type: {
        name: "number",
        required: false
      },
      description: "Specifies the current value for a range input.",
      defaultValue: 0,
      control: {
        type: "number"
      },
    },
    ariaValuetext: {
      type: {
        name: "string",
        required: false
      },
      description: "Provides a human-readable representation of the current value.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    autocapitalize: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "none", "sentences", "words", "characters"],
    },
    autofocus: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    classProp: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    contenteditable: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "true", "false", "inherit"],
    },
    data: {
      type: {
        name: "object",
        required: false
      },
      description: "Custom data attributes (data-*). Provide an object with key-value pairs.",
      defaultValue: {},
      control: {
        type: "object"
      },
    },
    dir: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "ltr", "rtl", "auto"],
    },
    draggable: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    hidden: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    high: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the high value for a range input or a meter element.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    id: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    inputmode: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "none", "text", "decimal", "numeric", "email", "tel", "url", "search"],
    },
    lang: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    low: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the low value for a range input.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    max: {
      type: {
        name: "number",
        required: false
      },
      description: "Specifies the maximum value for an input element, meter, or progress element.",
      defaultValue: 0,
      control: {
        type: "number"
      },
    },
    min: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the minimum value for an input element or a meter element.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    optimum: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the optimal value for a gauge or progress element.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    slot: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    spellcheck: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "true", "false"],
    },
    style: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    tabindex: {
      type: {
        name: "number",
        required: false
      },
      defaultValue: 0,
      control: {
        type: "number"
      },
    },
    title: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    translate: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "yes", "no"],
    },
    value: {
      type: {
        name: "string",
        required: false
      },
      description: "Specifies the value associated with the element. The meaning and usage may vary depending on the element type.",
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
  },
  render: ({
    text,
    accesskey,
    ariaAtomic,
    ariaDetails,
    ariaKeyshortcuts,
    ariaLive,
    ariaRelevant,
    ariaRoledescription,
    ariaValuemax,
    ariaValuemin,
    ariaValuenow,
    ariaValuetext,
    autocapitalize,
    autofocus,
    classProp,
    contenteditable,
    data,
    dir,
    draggable,
    hidden,
    high,
    id,
    inputmode,
    lang,
    low,
    max,
    min,
    optimum,
    slot,
    spellcheck,
    style,
    tabindex,
    title,
    translate,
    value,
  }) => {
    let el = document.createElement("meter");
    el.innerHTML = text;
    if (accesskey) {
      el.setAttribute('accesskey', accesskey);
    }
    if (ariaAtomic) {
      el.setAttribute('aria-atomic', ariaAtomic);
    }
    if (ariaDetails) {
      el.setAttribute('aria-details', ariaDetails);
    }
    if (ariaKeyshortcuts) {
      el.setAttribute('aria-keyshortcuts', ariaKeyshortcuts);
    }
    if (ariaLive) {
      el.setAttribute('aria-live', ariaLive);
    }
    if (ariaRelevant) {
      el.setAttribute('aria-relevant', ariaRelevant);
    }
    if (ariaRoledescription) {
      el.setAttribute('aria-roledescription', ariaRoledescription);
    }
    if (ariaValuemax) {
      el.setAttribute('aria-valuemax', ariaValuemax);
    }
    if (ariaValuemin) {
      el.setAttribute('aria-valuemin', ariaValuemin);
    }
    if (ariaValuenow) {
      el.setAttribute('aria-valuenow', ariaValuenow);
    }
    if (ariaValuetext) {
      el.setAttribute('aria-valuetext', ariaValuetext);
    }
    if (autocapitalize) {
      el.setAttribute('autocapitalize', autocapitalize);
    }
    if (autofocus) {
      el.setAttribute('autofocus', autofocus);
    }
    if (classProp) {
      el.setAttribute('class', classProp);
    }
    if (contenteditable) {
      el.setAttribute('contenteditable', contenteditable);
    }
    if (data && typeof data === 'object') {
      Object.keys(data).forEach(key => {
        el.setAttribute(`data-${key}`, data[key]);
      });
    }
    if (dir) {
      el.setAttribute('dir', dir);
    }
    if (draggable) {
      el.setAttribute('draggable', draggable);
    }
    if (hidden) {
      el.setAttribute('hidden', hidden);
    }
    if (high) {
      el.setAttribute('high', high);
    }
    if (id) {
      el.setAttribute('id', id);
    }
    if (inputmode) {
      el.setAttribute('inputmode', inputmode);
    }
    if (lang) {
      el.setAttribute('lang', lang);
    }
    if (low) {
      el.setAttribute('low', low);
    }
    if (max) {
      el.setAttribute('max', max);
    }
    if (min) {
      el.setAttribute('min', min);
    }
    if (optimum) {
      el.setAttribute('optimum', optimum);
    }
    if (slot) {
      el.setAttribute('slot', slot);
    }
    if (spellcheck) {
      el.setAttribute('spellcheck', spellcheck);
    }
    if (style) {
      el.setAttribute('style', style);
    }
    if (tabindex) {
      el.setAttribute('tabindex', tabindex);
    }
    if (title) {
      el.setAttribute('title', title);
    }
    if (translate) {
      el.setAttribute('translate', translate);
    }
    if (value) {
      el.setAttribute('value', value);
    }
    return el;
  },
  decorators: [],
};

export const Default = {
  parameters: {
    docs: {
      description: {
        story: 'Default story with all arguments set to default values'
      },
    },
  },
  args: {
    text: "Sample text",
    accesskey: "Sample value",
    ariaAtomic: "",
    ariaDetails: "Sample value",
    ariaKeyshortcuts: "Sample value",
    ariaLive: "",
    ariaRelevant: "",
    ariaRoledescription: "Sample value",
    ariaValuemax: 0,
    ariaValuemin: 0,
    ariaValuenow: 0,
    ariaValuetext: "Sample value",
    autocapitalize: "",
    autofocus: false,
    classProp: "Sample value",
    contenteditable: "",
    data: {},
    dir: "",
    draggable: false,
    hidden: false,
    high: "Sample value",
    id: "Sample value",
    inputmode: "",
    lang: "Sample value",
    low: "Sample value",
    max: 0,
    min: "Sample value",
    optimum: "Sample value",
    slot: "Sample value",
    spellcheck: "",
    style: "Sample value",
    tabindex: 0,
    title: "Sample value",
    translate: "",
    value: "Sample value",
  },
};
