/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated November 13, 2025 17:52:41
 * @component Parameter
 * @description The param element defines parameters for an object element.
 */

import React from 'react';

export interface ParamProps {
  /** CSS class names */
  className?: string;
  /** Custom data attributes (data-*) */
  data?: Record<string, string>;
  hidden?: boolean;
  id?: string;
  /** Specifies the name associated with the element. The meaning may vary depending on the context. */
  name?: string;
  style?: React.CSSProperties;
  /** Specifies the value associated with the element. The meaning and usage may vary depending on the element type. */
  value?: string;
}

/**
 * Parameter - The param element defines parameters for an object element.
 */
export const Param: React.FC<ParamProps> = (props: ParamProps) => {
  const {
    className,
    data,
    hidden,
    id,
    name,
    style,
    value
  } = props;

  const elementProps: React.HTMLAttributes<HTMLElement> & Record<string, any> = {};

  // Handle data attributes specially
  if (data) {
    Object.entries(data).forEach(([key, value]) => {
      elementProps[`data-${key}`] = value;
    });
  }

  // Convert camelCase to kebab-case for attribute names
  const toKebabCase = (str: string): string => {
    return str.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
  };

  // Props to exclude from automatic mapping
  const excludedProps = new Set(['children', 'data']);

  // Iterate over all props and map them to element attributes
  Object.entries(props).forEach(([key, value]) => {
    if (excludedProps.has(key) || value === undefined) {
      return;
    }

    // Convert camelCase aria/contenteditable/autocapitalize to kebab-case
    const attrName = key.startsWith('aria') || key === 'contenteditable' || key === 'autocapitalize' 
      ? toKebabCase(key)
      : key;

    // Handle boolean props that need explicit conversion
    if (typeof value === 'boolean' && (key === 'hidden')) {
      elementProps[attrName] = value ? true : false;
    } else {
      elementProps[attrName] = value;
    }
  });

  return React.createElement(
    'param',
    elementProps
  );
};

Param.displayName = 'Param';
